import type { GameEvent } from '../engine/types';

/**
 * Content pack 8 — eighth volume expansion. Recall petitions, micro-targeting,
 * and broken pledges (ballot); loyalty questionnaires, fabricated hero-workers,
 * and recalled exiles (vanguard); biopics, lavish gifts, and defeated rivals
 * (shared); and five new crises (volcano, offshore spill, foreign blackmail,
 * mass poisoning, prison uprising). Fictional and non-partisan by construction.
 */
export const PACK_8: GameEvent[] = [
  // ---------------- BALLOT ----------------
  {
    id: 'p8_b_recall',
    paths: ['ballot'],
    phases: [2, 3],
    weight: 7,
    art: 'newspaper',
    emoji: '🗳️',
    title: 'The Recall Petition',
    body: `Your opponents have gathered enough signatures to force a mid-term recall vote. You can spend a fortune fighting it or dare them to actually win.`,
    choices: [
      {
        label: 'Take it seriously; campaign hard',
        fx: { support: 8, funds: -10, base: 4 },
        tone: 'good',
        result: 'You treat the threat with respect and grind out the win. Expensive, exhausting, and survived.',
      },
      {
        label: 'Dismiss it as a stunt',
        roll: {
          stat: 'base',
          dc: 52,
          success: {
            fx: { base: 8, support: 4 },
            text: 'Your confidence proves justified; the recall fizzles and you look unflappable.',
          },
          fail: {
            fx: { support: -12, heat: 6 },
            text: 'You blink too late. The "stunt" nearly takes your head off, and the near-miss is the story.',
          },
        },
        tone: 'bold',
      },
    ],
  },
  {
    id: 'p8_b_microtarget',
    paths: ['ballot'],
    phases: [2, 3],
    weight: 6,
    art: 'scene',
    emoji: '🎯',
    title: 'The Data Firm',
    body: `A slick data firm offers to micro-target voters with eerily personalized messaging built from data they will not fully explain how they got.`,
    choices: [
      {
        label: 'Hire them; the edge is decisive',
        fx: { media: 8, support: 6, heat: 8 },
        set: { corrupt_streak: true },
        scandal: { id: 'data_firm', label: 'the data firm’s mystery sources', severity: 2 },
        tone: 'slick',
        result: 'The targeting is uncanny and effective. Where exactly all that personal data came from is a question for later.',
      },
      {
        label: 'Pass; keep it clean',
        fx: { support: 2, base: 4 },
        set: { clean_streak: true },
        tone: 'good',
        result: 'You decline the creepy edge and campaign the old way. Slower, squarer, and you sleep fine.',
      },
    ],
  },
  {
    id: 'p8_b_pledge_break',
    paths: ['ballot'],
    phases: [2, 3],
    weight: 7,
    art: 'bulletin',
    emoji: '🤞',
    title: 'The Broken Pledge',
    body: `Reality has made your signature campaign promise impossible to keep. You can break it honestly now or keep pretending it is still on the way.`,
    choices: [
      {
        label: 'Admit it can’t be done, explain why',
        fx: { support: 6, base: -4, media: 2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You break the promise out loud and own the reasons. Painful, clean, and oddly trust-building.',
      },
      {
        label: 'Keep dangling it indefinitely',
        fx: { base: 4, heat: 6, support: -2 },
        tone: 'slick',
        result: 'You promise it is "still coming" for the tenth time. The base half-believes; the press counts the months.',
      },
    ],
  },
  {
    id: 'p8_b_empty_chair',
    paths: ['ballot'],
    phases: [3],
    weight: 7,
    art: 'rival',
    emoji: '🪑',
    title: 'The Empty Chair',
    speaker: (S) => ({ name: S.opp, role: 'your rival', avatar: S.oppAvatar }),
    body: (S) =>
      `${S.opp} is ducking the big debate. You can debate an empty chair for the cameras or graciously let it go and look like the bigger person.`,
    choices: [
      {
        label: 'Debate the empty chair theatrically',
        roll: {
          stat: 'media',
          dc: 50,
          success: {
            fx: { media: 10, base: 6 },
            text: 'You turn the no-show into a viral spectacle of your rival’s cowardice. The chair never recovers.',
          },
          fail: {
            fx: { support: -6, media: -2 },
            text: 'The stunt reads as desperate and a little unhinged. You lost a debate to furniture.',
          },
        },
        npcFx: { id: 'antagonist', relationship: -10 },
        tone: 'bold',
      },
      {
        label: 'Take the high road',
        fx: { support: 6, base: 2 },
        tone: 'good',
        result: 'You decline to mock and simply note their absence. Restraint, for once, scores the cleaner point.',
      },
    ],
  },
  {
    id: 'p8_b_veterans',
    paths: ['ballot'],
    phases: [1, 2, 3],
    weight: 7,
    art: 'scene',
    emoji: '🎖️',
    title: 'The Veterans’ Fight',
    body: `Aging veterans are owed benefits the budget "cannot find." They are sympathetic, organized, and standing on your steps with cameras and medals.`,
    choices: [
      {
        label: 'Find the money for them',
        fx: { support: 10, funds: -8, base: 4 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You move the money and pay the debt owed. Some bills you simply do not get to argue with.',
      },
      {
        label: 'Offer warm words and a study committee',
        fx: { media: 4, support: -6, heat: 4 },
        tone: 'slick',
        result: 'You honor their service with a podium and a committee. The medals on your steps are not fooled.',
      },
    ],
  },
  {
    id: 'p8_b_staffer_scandal',
    paths: ['ballot'],
    phases: [1, 2, 3],
    weight: 6,
    art: 'newspaper',
    emoji: '🚪',
    title: 'The Staffer’s Mess',
    body: `A senior staffer has gotten themselves into a tabloid scandal that is splashing onto you. They are talented, loyal, and currently radioactive.`,
    choices: [
      {
        label: 'Stand by them through the storm',
        fx: { base: 4, heat: 8, support: -4 },
        set: { loyal_to_old_friends: true },
        tone: 'good',
        result: 'You refuse to fire a good person for a bad week. Loyalty, costly and visible, earns a fierce kind of devotion.',
      },
      {
        label: 'Cut them loose to stop the bleeding',
        fx: { media: 4, support: 4, base: -4 },
        tone: 'slick',
        result: 'You accept their resignation by lunch. The story ends; your remaining staff updates their résumés quietly.',
      },
    ],
  },
  {
    id: 'p8_b_billboard',
    paths: ['ballot'],
    phases: [2, 3],
    weight: 6,
    art: 'rival',
    emoji: '🪧',
    title: 'The Billboard War',
    speaker: (S) => ({ name: S.opp, role: 'your rival', avatar: S.oppAvatar }),
    body: (S) =>
      `${S.opp} has plastered the highways with a billboard mocking you by name. Your team has a brutal comeback design ready to print.`,
    choices: [
      {
        label: 'Answer with a savage billboard of your own',
        fx: { media: 6, base: 6, heat: 6, support: -2 },
        npcFx: { id: 'antagonist', relationship: -12 },
        tone: 'bold',
        result: 'The highways become a slugfest in vinyl. Your base loves it; commuters are exhausted by both of you.',
      },
      {
        label: 'Buy the adjacent space for a positive message',
        fx: { support: 8, media: 4, funds: -4 },
        tone: 'good',
        result: 'Right beside their attack, you put up something hopeful. The contrast does the work the insult couldn’t.',
      },
    ],
  },
  {
    id: 'p8_b_water_project',
    paths: ['ballot'],
    phases: [1, 2],
    weight: 6,
    art: 'bulletin',
    emoji: '🚰',
    title: 'The Cheap Pipes',
    body: `Your flagship public-water project is over budget. You can use the cheaper pipes and cut the ribbon on time, or eat the delay and use the safe ones.`,
    choices: [
      {
        label: 'Use the safe pipes; eat the delay',
        fx: { support: 6, funds: -6, base: 2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You miss the ribbon-cutting date and build it right. Boring, slow, and nobody gets sick in five years.',
      },
      {
        label: 'Cut the corner, hit the deadline',
        fx: { base: 8, media: 4, heat: 6 },
        scandal: { id: 'cheap_pipes', label: 'the corners cut on the water project', severity: 2 },
        tone: 'slick',
        result: 'You cut the ribbon on schedule to applause. The pipes are a problem deferred, with your signature on the spec.',
      },
    ],
  },

  // ---------------- VANGUARD ----------------
  {
    id: 'p8_v_questionnaire',
    paths: ['vanguard'],
    phases: [1, 2],
    weight: 7,
    art: 'bulletin',
    emoji: '📝',
    title: 'The Loyalty Questionnaire',
    body: `A new vetting form is to be circulated through your department — invasive questions designed to flush out the insufficiently devoted. You administer it, or you don’t.`,
    choices: [
      {
        label: 'Administer it zealously',
        fx: { base: 8, influence: 4, support: -6 },
        inc: { purge_count: 1 },
        set: { zealot_rep: true },
        tone: 'bold',
        result: 'You score every answer and flag the doubters. Your department grows quieter, warier, and thinner.',
      },
      {
        label: 'Lose half the forms; pass everyone',
        roll: {
          stat: 'influence',
          dc: 52,
          success: {
            fx: { support: 8, heat: 2 },
            text: 'You quietly clear your people through a bureaucratic fog. Nobody is purged on your watch.',
          },
          fail: {
            fx: { heat: 10, support: -4 },
            text: 'Your suspiciously clean results draw a second auditor. Leniency, here, is itself suspicious.',
          },
        },
        set: { secret_reformer: true },
        tone: 'slick',
      },
    ],
  },
  {
    id: 'p8_v_hero_worker',
    paths: ['vanguard'],
    phases: [1, 2],
    weight: 7,
    art: 'newspaper',
    emoji: '⛏️',
    title: 'The Hero Worker',
    body: `Propaganda wants a record-smashing "hero worker" from your region for the front pages. The real workers are tired and ordinary; the record would have to be invented.`,
    choices: [
      {
        label: 'Manufacture the legend',
        fx: { media: 10, influence: 6, heat: 4 },
        set: { potemkin: true },
        tone: 'slick',
        result: 'You anoint a hero and fabricate his impossible numbers. The nation gets a poster; the truth gets a footnote.',
      },
      {
        label: 'Honor a real, modest worker instead',
        fx: { support: 8, base: 4, influence: -2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You celebrate someone genuinely good at an ordinary job. The story is smaller and, rarely here, true.',
      },
    ],
  },
  {
    id: 'p8_v_exile_return',
    paths: ['vanguard'],
    phases: [2, 3],
    weight: 7,
    art: 'rival',
    emoji: '🛬',
    title: 'The Recalled Exile',
    body: `A rival you once exiled is to be invited home — ostensibly forgiven, actually to be quietly destroyed where he can be watched. You are to extend the warm, lethal welcome.`,
    choices: [
      {
        label: 'Spring the trap as ordered',
        fx: { influence: 8, base: 6, support: -6, heat: 4 },
        inc: { purge_count: 1 },
        set: { bloody_hands: true },
        tone: 'bold',
        result: 'You greet him with an embrace and a noose behind your back. The Centre is pleased with your craftsmanship.',
      },
      {
        label: 'Quietly warn him not to come',
        fx: { support: 8, influence: -6, heat: 8 },
        set: { secret_reformer: true },
        tone: 'good',
        result: 'A coded message reaches him in time and he stays away. The trap closes on empty air, and someone wonders why.',
      },
    ],
  },
  {
    id: 'p8_v_informant_web',
    paths: ['vanguard'],
    phases: [1, 2, 3],
    weight: 6,
    art: 'scene',
    emoji: '🕸️',
    title: 'The Informant Web',
    body: `You can expand your network of informants until every kitchen table has an ear at it. Total knowledge, total paranoia, and a machine that, once built, is hard to switch off.`,
    choices: [
      {
        label: 'Weave the web tight',
        fx: { influence: 12, base: 4, heat: 8, support: -6 },
        set: { has_network: true, blackmailer: true },
        tone: 'slick',
        result: 'You hear everything now, including your own name in frightened whispers. Omniscience has a temperature, and it is cold.',
      },
      {
        label: 'Keep it small and targeted',
        fx: { influence: 6, heat: 2 },
        tone: 'good',
        result: 'You resist the temptation to bug the whole republic. A smaller web, a marginally warmer country.',
      },
    ],
  },
  {
    id: 'p8_v_relic',
    paths: ['vanguard'],
    phases: [2, 3],
    weight: 6,
    art: 'scene',
    emoji: '⛪',
    title: 'The Old Cathedral',
    body: `The Centre wants the ancient cathedral demolished as a symbol of the dead order. It is also the only beautiful thing for a hundred miles, and the people love it.`,
    choices: [
      {
        label: 'Quietly convert it, don’t destroy it',
        fx: { support: 10, base: -4, heat: 6 },
        set: { secret_reformer: true },
        tone: 'good',
        result: 'You turn it into a museum of the people instead of rubble. The stone survives; your orthodoxy is quietly questioned.',
      },
      {
        label: 'Demolish it for the cameras',
        fx: { base: 10, media: 4, support: -8 },
        tone: 'bold',
        result: 'The domes come down in a cloud of dust and applause from the right people. The province mourns in careful silence.',
      },
    ],
  },
  {
    id: 'p8_v_self_medal',
    paths: ['vanguard'],
    phases: [3],
    weight: 6,
    art: 'bulletin',
    emoji: '🏅',
    title: 'The Medal',
    body: `It is within your power to have yourself awarded the republic’s highest honor for "services to the people." No one would dare object. That is rather the point.`,
    choices: [
      {
        label: 'Pin it on yourself',
        fx: { base: 8, media: 4, support: -6, heat: 4 },
        set: { own_cult: true },
        tone: 'bold',
        result: 'You award yourself the highest medal in the land. The applause is thunderous and entirely compulsory.',
      },
      {
        label: 'Award it to a fallen soldier’s family instead',
        fx: { support: 12, base: 2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You give the honor to a grieving family on a quiet stage. The restraint says more than any medal on your chest.',
      },
    ],
  },
  {
    id: 'p8_v_border_pretext',
    paths: ['vanguard'],
    phases: [2, 3],
    weight: 7,
    art: 'crisis',
    emoji: '🎇',
    title: 'The Convenient Incident',
    body: `The Centre would find a small, manageable border "incident" very useful right now — a flag to rally behind. You could manufacture one. People might get hurt for the theater of it.`,
    choices: [
      {
        label: 'Stage the incident',
        fx: { base: 10, media: 8, heat: 8, support: -4 },
        inc: { purge_count: 1 },
        set: { bloody_hands: true },
        scandal: { id: 'false_flag', label: 'the incident you staged', severity: 3 },
        tone: 'bold',
        result: 'A scripted skirmish lights up the news and the flags come out. A few real people pay for the convenient drama.',
      },
      {
        label: 'Refuse to manufacture a crisis',
        fx: { support: 8, influence: -4, base: 2 },
        set: { honest_rep: true, peacemaker: true },
        tone: 'good',
        result: 'You decline to spill real blood for a propaganda banner. The Centre is irritated; your conscience is not.',
      },
    ],
  },
  {
    id: 'p8_v_singer',
    paths: ['vanguard'],
    phases: [2, 3],
    weight: 6,
    art: 'scene',
    emoji: '🎤',
    title: 'The Defiant Singer',
    body: `The nation’s most beloved singer has politely declined to perform at your festival — a small, public, dangerous "no." How you respond will be sung about, one way or another.`,
    choices: [
      {
        label: 'Let it go gracefully',
        fx: { support: 8, media: 4, base: -2 },
        set: { secret_reformer: true },
        tone: 'good',
        result: 'You shrug and wish them well in public. Magnanimity defuses what a tantrum would have detonated.',
      },
      {
        label: 'Make their life difficult',
        fx: { base: 8, heat: 8, support: -8 },
        inc: { purge_count: 1 },
        set: { tyrant_rep: true },
        tone: 'bold',
        result: 'You see to it their tours dry up and their friends grow nervous. The whole country notices who you are now.',
      },
    ],
  },

  // ---------------- SHARED ----------------
  {
    id: 'p8_s_biopic',
    paths: ['ballot', 'vanguard'],
    phases: [3],
    weight: 6,
    art: 'newspaper',
    emoji: '🎥',
    title: 'The Biopic',
    body: `A famous director is making a film of your life. The script is flattering but invents a heroic moment that never happened. You can correct it or let the legend harden.`,
    choices: [
      {
        label: 'Insist on the truth, flaws and all',
        fx: { support: 8, media: 4, base: -2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You make them cut the invented heroics. The film is smaller, truer, and you can watch it without wincing.',
      },
      {
        label: 'Let the flattering myth stand',
        fx: { media: 10, base: 6, heat: 2 },
        set: { cult_building: true },
        tone: 'slick',
        result: 'You let the cinematic lie become the memory. In a generation, no one will know it was invented. That is the danger.',
      },
    ],
  },
  {
    id: 'p8_s_lavish_gift',
    paths: ['ballot', 'vanguard'],
    phases: [1, 2, 3],
    weight: 6,
    art: 'scene',
    emoji: '🐎',
    title: 'The Extravagant Gift',
    body: `A foreign leader has gifted you something absurdly valuable — a jeweled saddle, a gold-plated car. Keeping it is a scandal; refusing it is a diplomatic insult.`,
    choices: [
      {
        label: 'Donate it to the national museum',
        fx: { support: 8, media: 4, funds: -2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You accept it graciously and hand it straight to the public collection. The insult is dodged, the scandal defused.',
      },
      {
        label: 'Quietly keep it',
        fx: { funds: 8, heat: 8, support: -4 },
        set: { corrupt_streak: true },
        scandal: { id: 'kept_gift', label: 'the gift you quietly kept', severity: 1 },
        tone: 'slick',
        result: 'The gorgeous thing finds a home in your residence. An inventory of state gifts exists, and someday someone reads it.',
      },
    ],
  },
  {
    id: 'p8_s_defeated_rival',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 6,
    art: 'rival',
    emoji: '🤝',
    title: 'The Defeated Rival',
    speaker: (S) => ({ name: S.opp, role: 'your beaten rival', avatar: S.oppAvatar }),
    body: (S) =>
      `You have beaten ${S.opp} decisively, and now they sit before you, diminished. You could offer them a real post — talent is talent — or savor the win and leave them out in the cold.`,
    choices: [
      {
        label: 'Offer them a genuine role',
        fx: { influence: 8, support: 6, base: -2 },
        npcFx: { id: 'antagonist', relationship: 18 },
        set: { has_network: true },
        tone: 'good',
        result: 'You put your old enemy to work. A rival inside the tent is a strange comfort, and a useful one.',
      },
      {
        label: 'Leave them in the cold',
        fx: { base: 6, heat: 2, support: -2 },
        npcFx: { id: 'antagonist', relationship: -8 },
        tone: 'slick',
        result: 'You let them rot in irrelevance. Satisfying, and a free supply of motivated enemies for later.',
      },
    ],
  },
  {
    id: 'p8_s_sick_child',
    paths: ['ballot', 'vanguard'],
    phases: [1, 2, 3],
    weight: 6,
    art: 'scene',
    emoji: '🧸',
    title: 'The Hospital Visit',
    body: `A gravely ill child has, touchingly, asked to meet you. It would be a genuine kindness — and your handlers, who never miss an angle, want the cameras there.`,
    choices: [
      {
        label: 'Go quietly, no cameras',
        fx: { support: 6, base: 4, media: -2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You visit privately and tell no one. The kindness is real precisely because no one was watching.',
      },
      {
        label: 'Bring the press for the moment',
        roll: {
          stat: 'media',
          dc: 50,
          success: {
            fx: { media: 10, support: 6 },
            text: 'The image of genuine tenderness moves the nation. It was real and it was useful; both can be true.',
          },
          fail: {
            fx: { support: -8, heat: 4 },
            text: 'The cameras make it look staged and the family looks uncomfortable. Exploiting a sick child reads exactly as badly as it is.',
          },
        },
        tone: 'slick',
      },
    ],
  },
  {
    id: 'p8_s_war_anniversary',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 6,
    art: 'bulletin',
    emoji: '🌹',
    title: 'The War Anniversary',
    body: `It is the anniversary of a terrible war, and you must give the address. You can tell the comforting national myth, or the harder, truer story that honors the dead more honestly.`,
    choices: [
      {
        label: 'Tell the difficult truth',
        fx: { support: 8, base: -2, media: 2 },
        set: { honest_rep: true, peacemaker: true },
        tone: 'good',
        result: 'You name the war’s real cost and folly, gently. Some bristle; the veterans in the front row nod slowly.',
      },
      {
        label: 'Wrap them in the comforting myth',
        fx: { base: 8, media: 6, support: 2 },
        tone: 'slick',
        result: 'You give them glory, sacrifice, and a clean story. It soothes and it flatters and it teaches nothing.',
      },
    ],
  },
  {
    id: 'p8_s_vote_irregularity',
    paths: ['ballot', 'vanguard'],
    phases: [3],
    weight: 6,
    art: 'newspaper',
    emoji: '🧮',
    title: 'The Irregular Count',
    body: `Whispers say a district reported suspiciously perfect numbers in your favor. Looking into it risks finding something; ignoring it risks someone else finding it first.`,
    choices: [
      {
        label: 'Order an honest audit yourself',
        fx: { support: 8, base: 2, heat: -4 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You call for scrutiny of your own win. If it is clean, you look fearless; if not, better you find it.',
      },
      {
        label: 'Let the perfect numbers stand',
        fx: { base: 4, heat: 10, support: -4 },
        scandal: { id: 'perfect_count', label: 'the district’s too-perfect tally', severity: 2 },
        tone: 'slick',
        result: 'You decide not to look too closely at good news. The number stands, and so does the question mark over it.',
      },
    ],
  },
  {
    id: 'p8_s_ghost_advisor',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 6,
    art: 'scene',
    emoji: '🎙️',
    title: 'The Whispering Advisor',
    body: `A brilliant, ruthless advisor has your ear and a genius for the dark arts of power. They make you more effective and, week by week, a little more like them.`,
    choices: [
      {
        label: 'Keep them close',
        fx: { influence: 10, base: 4, heat: 6 },
        set: { has_network: true },
        tone: 'slick',
        result: 'You let the whisperer guide your hand. You win more often, and recognize yourself a little less.',
      },
      {
        label: 'Send them away while you still can',
        fx: { support: 6, influence: -4, base: 2 },
        set: { clean_streak: true },
        tone: 'good',
        result: 'You dismiss the dark genius before they finish remaking you. A harder road, walked as yourself.',
      },
    ],
  },

  // ---------------- CRISES ----------------
  {
    id: 'p8_c_volcano',
    paths: ['ballot', 'vanguard'],
    phases: [1, 2, 3],
    weight: 8,
    crisis: true,
    art: 'crisis',
    emoji: '🌋',
    title: 'The Ashfall',
    body: `A volcano has buried the eastern farms in ash and grounded every flight in the country. The harvest is gone, the air is grey, and the people need a plan by nightfall.`,
    choices: [
      {
        label: 'Mobilize a massive, visible relief effort',
        fx: { support: 12, funds: -10, base: 4 },
        tone: 'good',
        result: 'You throw the full weight of the state at the ash. Costly, competent, and the right kind of memorable.',
      },
      {
        label: 'Downplay it to protect the markets',
        roll: {
          stat: 'media',
          dc: 52,
          success: {
            fx: { media: 6, funds: 4 },
            text: 'You keep the panic and the markets calm with careful framing. The ash settles before the story does.',
          },
          fail: {
            fx: { support: -12, heat: 8 },
            text: 'Your "all is well" collides with grey skies on every screen. Denial, photographed, becomes the scandal.',
          },
        },
        tone: 'slick',
      },
    ],
  },
  {
    id: 'p8_c_oil_spill',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 8,
    crisis: true,
    art: 'crisis',
    emoji: '🛢️',
    title: 'The Spill',
    body: `An offshore rig has ruptured and a black tide is creeping toward the coast. The company that runs it is a major backer, and they would very much like you to go easy.`,
    choices: [
      {
        label: 'Hammer the company; lead the cleanup',
        fx: { support: 12, funds: -6, heat: -2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You make the polluter pay and front the cleanup yourself. A backer is furious; a coastline is grateful.',
      },
      {
        label: 'Go easy on your backer',
        fx: { funds: 8, heat: 10, support: -8 },
        set: { corrupt_streak: true },
        scandal: { id: 'spill_favor', label: 'the polluter you protected', severity: 3 },
        tone: 'slick',
        result: 'You soften the blow for your friends in oil. The slick reaches the beaches, and so, eventually, do the questions.',
      },
    ],
  },
  {
    id: 'p8_c_blackmail',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 8,
    crisis: true,
    art: 'crisis',
    emoji: '📑',
    title: 'The Blackmail',
    body: `A foreign service has something real on you and will quietly trade its silence for a small betrayal of your country’s interests. The clock on the table is theirs.`,
    choices: [
      {
        label: 'Refuse; brace for the exposure',
        roll: {
          stat: 'support',
          dc: 54,
          success: {
            fx: { support: 12, base: 8, heat: -6 },
            text: 'You call their bluff and pre-empt them with a confession of your own. Owning it strips their weapon bare.',
          },
          fail: {
            fx: { support: -10, heat: 10 },
            text: 'They release it anyway and it stings hard. But you betrayed nothing, and that, later, will matter.',
          },
        },
        set: { honest_rep: true },
        tone: 'bold',
      },
      {
        label: 'Pay their price in secret',
        fx: { influence: 4, heat: 12, support: -6 },
        set: { compromised: true, foreign_friends: true },
        scandal: { id: 'blackmail_paid', label: 'the secret you sold to bury a secret', severity: 4 },
        tone: 'slick',
        result: 'You make the quiet betrayal and the file stays buried. You are safe, and you belong to them now.',
      },
    ],
  },
  {
    id: 'p8_c_poisoning',
    paths: ['ballot', 'vanguard'],
    phases: [1, 2, 3],
    weight: 8,
    crisis: true,
    art: 'crisis',
    emoji: '🥫',
    title: 'The Tainted Supply',
    body: `A staple food has been contaminated and people are falling ill across the country. A full recall will cause shortages and panic; a quiet one risks more sickness.`,
    choices: [
      {
        label: 'Order an immediate, total recall',
        fx: { support: 12, funds: -8, base: 2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You pull every can from every shelf and explain why on every channel. Empty shelves, full trust.',
      },
      {
        label: 'Recall quietly to avoid panic',
        roll: {
          stat: 'media',
          dc: 53,
          success: {
            fx: { media: 4, support: 4 },
            text: 'You manage a discreet recall and the outbreak fades without a stampede. Threaded, narrowly.',
          },
          fail: {
            fx: { support: -14, heat: 12 },
            text: 'The quiet recall is too slow and the illness spreads. "They knew and stayed quiet" is the headline now.',
          },
        },
        scandal: { id: 'quiet_recall', label: 'the outbreak you kept quiet', severity: 2 },
        tone: 'slick',
      },
    ],
  },
  {
    id: 'p8_c_prison',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 8,
    crisis: true,
    art: 'crisis',
    emoji: '⛓️',
    title: 'The Prison Uprising',
    body: `Inmates have seized a wing and taken guards hostage, broadcasting grievances about conditions that are, embarrassingly, true. The siege is live on every channel.`,
    choices: [
      {
        label: 'Negotiate and reform the conditions',
        roll: {
          stat: 'support',
          dc: 52,
          success: {
            fx: { support: 12, base: 4, influence: 4 },
            text: 'You concede the legitimate grievances and the hostages walk free. Addressing the rot ends the revolt.',
          },
          fail: {
            fx: { support: -6, heat: 8 },
            text: 'Your concessions are spun as caving to criminals. Doing the humane thing wins you no points and a hard week.',
          },
        },
        set: { peacemaker: true },
        tone: 'good',
      },
      {
        label: 'Storm the wing',
        fx: { base: 8, heat: 12, support: -6 },
        inc: { purge_count: 1 },
        set: { bloody_hands: true },
        tone: 'bold',
        result: 'You send the teams in and the siege ends hard and fast. The cameras catch all of it, and so does history.',
      },
    ],
  },
];
