import type { GameEvent } from '../engine/types';

/**
 * Content pack 6 — sixth volume expansion. War votes, faith leaders, and
 * spoiler candidates (ballot); spy rings, re-education, and succession plots
 * (vanguard); international prizes and dying rivals (shared); and five new
 * crises (drought, coup attempt, hostage crisis, flood, pandemic wave).
 * Fictional and non-partisan by construction.
 */
export const PACK_6: GameEvent[] = [
  // ---------------- BALLOT ----------------
  {
    id: 'p6_b_war_vote',
    paths: ['ballot'],
    phases: [2, 3],
    weight: 8,
    art: 'bulletin',
    emoji: '⚔️',
    title: 'The Strike Authorization',
    body: `Intelligence is thin and the drums are loud: you can authorize a military strike that will look decisive, or hold back and look cautious while rivals call it weakness.`,
    choices: [
      {
        label: 'Hold back; demand better intelligence',
        roll: {
          stat: 'support',
          dc: 52,
          success: {
            fx: { support: 12, influence: 6, base: -2 },
            text: 'You refuse to be stampeded, the intelligence proves shaky, and your restraint ages into wisdom.',
          },
          fail: {
            fx: { support: -8, base: -4 },
            text: 'Caution reads as dithering and your rivals feast on it. Being right slowly is its own punishment.',
          },
        },
        set: { peacemaker: true },
        tone: 'good',
      },
      {
        label: 'Order the strike',
        fx: { base: 10, media: 6, heat: 10, support: -2 },
        tone: 'bold',
        result: 'You give the order and the flags come out. Whether history calls it decisive or reckless depends on what the dust reveals.',
      },
    ],
  },
  {
    id: 'p6_b_faith_leader',
    paths: ['ballot'],
    phases: [1, 2],
    weight: 7,
    art: 'scene',
    emoji: '⛪',
    title: 'The Pulpit’s Price',
    body: `A faith leader who can deliver a vast, devoted congregation will champion you — provided you echo their stance on a divisive moral question from the campaign stage.`,
    choices: [
      {
        label: 'Court the congregation',
        fx: { support: 10, base: 6, media: -2 },
        set: { owes_pulpit: true },
        tone: 'slick',
        result: 'The pews become your precincts. You also rent out a piece of your platform you cannot easily reclaim.',
      },
      {
        label: 'Keep faith and state at a respectful distance',
        fx: { support: -2, base: 4, influence: 4 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You thank them and decline the bargain. Principle costs you a bloc and buys you a clear conscience.',
      },
    ],
  },
  {
    id: 'p6_b_jobs_report',
    paths: ['ballot'],
    phases: [2, 3],
    weight: 7,
    art: 'newspaper',
    emoji: '📊',
    title: 'The Ugly Jobs Report',
    body: `The new economic numbers are grim and land the morning of a major speech. You can spin them frantically or simply level with people about a hard month.`,
    choices: [
      {
        label: 'Level with the public',
        fx: { support: 8, base: 4, media: 2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You name the bad number and your plan for it. Treating voters as adults is a surprisingly rare tactic.',
      },
      {
        label: 'Spin it furiously',
        roll: {
          stat: 'media',
          dc: 52,
          success: {
            fx: { media: 6, support: 4 },
            text: 'You find the one good sub-figure and ride it. The framing holds for a news cycle, which is all you needed.',
          },
          fail: {
            fx: { support: -8, heat: 4 },
            text: 'The spin is too obvious and becomes the story. "Out of touch" sticks like tar.',
          },
        },
        tone: 'slick',
      },
    ],
  },
  {
    id: 'p6_b_third_party',
    paths: ['ballot'],
    phases: [3],
    weight: 8,
    art: 'rival',
    emoji: '🎯',
    title: 'The Spoiler',
    body: `A charismatic third candidate is siphoning exactly the voters you need, and they know it. They will exit the race — for a promise you may not want to keep.`,
    choices: [
      {
        label: 'Cut the deal to clear the field',
        fx: { support: 10, influence: -4, heat: 4 },
        set: { dealmaker: true },
        tone: 'slick',
        result: 'They bow out and endorse you, with a wink toward the cabinet post you implied. The math improves; the debt accrues.',
      },
      {
        label: 'Beat them honestly at the ballot box',
        roll: {
          stat: 'base',
          dc: 53,
          success: {
            fx: { base: 10, support: 8 },
            text: 'You out-organize the spoiler and win their voters outright. No debt, no strings, just turnout.',
          },
          fail: {
            fx: { support: -8 },
            text: 'They hang in and bleed you to the end. The spoiler spoils; the margin pays for your pride.',
          },
        },
        tone: 'bold',
      },
    ],
  },
  {
    id: 'p6_b_immigration',
    paths: ['ballot'],
    phases: [2, 3],
    weight: 7,
    art: 'bulletin',
    emoji: '🛂',
    title: 'The Border Bill',
    body: `A sprawling compromise on immigration is on the table — humane in parts, harsh in others, and hated by the purists on both wings. Govern or grandstand.`,
    choices: [
      {
        label: 'Pass the messy compromise',
        fx: { influence: 8, support: 6, base: -6 },
        set: { dealmaker: true },
        tone: 'good',
        result: 'You hold your nose and pass something real. Both wings howl, which is often the sound of a genuine compromise.',
      },
      {
        label: 'Hold out for your wing’s pure version',
        fx: { base: 10, support: -4, heat: 4 },
        tone: 'bold',
        result: 'You refuse to deal and keep the issue alive for the next campaign. Nothing passes; the talking point thrives.',
      },
    ],
  },
  {
    id: 'p6_b_debate_leak',
    paths: ['ballot'],
    phases: [2, 3],
    weight: 6,
    art: 'rival',
    emoji: '📨',
    title: 'The Leaked Questions',
    speaker: (S) => ({ name: S.opp, role: 'your rival', avatar: S.oppAvatar }),
    body: (S) =>
      `A sympathetic insider slips you the debate questions in advance — a chance to bury ${S.opp} with "spontaneous" brilliance. It is also, unmistakably, cheating.`,
    choices: [
      {
        label: 'Refuse and report the leak',
        fx: { support: 8, base: 4, heat: -4 },
        set: { honest_rep: true, clean_streak: true },
        tone: 'good',
        result: 'You hand the questions back and flag the breach. Integrity nobody will ever see is still integrity.',
      },
      {
        label: 'Study them quietly',
        fx: { media: 8, support: 4, heat: 8 },
        scandal: { id: 'debate_leak', label: 'the debate questions you were slipped', severity: 2 },
        tone: 'slick',
        result: 'You walk in armored with foreknowledge and dazzle. Somewhere, a copy of that envelope still exists.',
      },
    ],
  },
  {
    id: 'p6_b_megadonor',
    paths: ['ballot'],
    phases: [1, 2, 3],
    weight: 7,
    art: 'scene',
    emoji: '💎',
    title: 'The Megadonor’s Wish',
    body: `A single staggeringly rich backer offers to fund your entire operation — in exchange for a quiet veto over one policy area they happen to care about enormously.`,
    choices: [
      {
        label: 'Take the money, grant the veto',
        fx: { funds: 16, media: 4, heat: 8 },
        set: { corrupt_streak: true, owes_donor: true },
        tone: 'slick',
        result: 'The coffers overflow. One small policy room is now, quietly, somebody else’s to decorate.',
      },
      {
        label: 'Decline and keep your hands free',
        fx: { base: 6, support: 4, funds: -4 },
        set: { clean_streak: true },
        tone: 'good',
        result: 'You turn down the fortune and the leash that came with it. A poorer, freer campaign.',
      },
    ],
  },

  // ---------------- VANGUARD ----------------
  {
    id: 'p6_v_birthday_festival',
    paths: ['vanguard'],
    phases: [2, 3],
    weight: 7,
    art: 'bulletin',
    emoji: '🎆',
    title: 'The Leader’s Birthday',
    body: `The aging leader’s birthday demands a spectacle, and you have been handed the budget and the staging. Outdo last year’s adoration, or quietly economize and risk the slight.`,
    choices: [
      {
        label: 'Stage the most lavish festival yet',
        fx: { influence: 8, base: 6, funds: -8, heat: 4 },
        set: { climber_rep: true },
        tone: 'slick',
        result: 'Fireworks, choirs, and a forty-foot portrait. The leader is pleased, the treasury is lighter, your stock rises.',
      },
      {
        label: 'A dignified, modest commemoration',
        fx: { support: 8, base: -2, funds: 2 },
        tone: 'good',
        result: 'You honor him without bankrupting a province. Some read restraint as respect; some read it as a threat.',
      },
    ],
  },
  {
    id: 'p6_v_spy_ring',
    paths: ['vanguard'],
    phases: [2, 3],
    weight: 7,
    art: 'crisis',
    emoji: '🕵️',
    title: 'The Spy Ring',
    body: `Counter-intelligence has rolled up a foreign spy ring, and the interrogations are producing names — some guilty, some merely convenient. The list is growing on your desk.`,
    choices: [
      {
        label: 'Pursue only the genuinely guilty',
        roll: {
          stat: 'influence',
          dc: 54,
          success: {
            fx: { influence: 8, support: 6, heat: -2 },
            text: 'You insist on evidence over convenience and catch the real ring. Precision earns a rare, wary respect.',
          },
          fail: {
            fx: { heat: 10, support: -4 },
            text: 'Your restraint is read as softness on traitors. The hardliners circle your "lenience."',
          },
        },
        set: { honest_rep: true },
        tone: 'good',
      },
      {
        label: 'Cast the net wide; settle old scores',
        fx: { base: 10, influence: 6, support: -8 },
        inc: { purge_count: 2 },
        set: { bloody_hands: true },
        tone: 'bold',
        result: 'You fold a dozen rivals into the "ring." The Centre is thrilled; the truth is now whatever the files say.',
      },
    ],
  },
  {
    id: 'p6_v_succession_plot',
    paths: ['vanguard'],
    phases: [3],
    weight: 9,
    art: 'rival',
    emoji: '🗡️',
    title: 'The Plot',
    speaker: (S) => ({ name: S.opp, role: 'a fellow conspirator', avatar: S.oppAvatar }),
    body: (S) =>
      `A cabal — ${S.opp} among them — quietly proposes to ease the failing leader aside. Join and you risk everything; refuse and you may be the loose end they tidy up.`,
    choices: [
      {
        label: 'Join the plot',
        fx: { influence: 10, base: 6, heat: 12 },
        set: { has_network: true, plotter: true },
        npcFx: { id: 'antagonist', relationship: 12 },
        tone: 'bold',
        result: 'You clasp the conspirators’ hands. You are now bound to people who have proven they will betray a leader.',
      },
      {
        label: 'Betray the plot to the leader',
        fx: { influence: 8, base: 8, support: -6, heat: 6 },
        inc: { purge_count: 1 },
        set: { bloody_hands: true },
        npcFx: { id: 'antagonist', relationship: -20 },
        tone: 'slick',
        result: 'You inform, and the plotters vanish overnight. The leader’s gratitude is real, and so is your new list of ghosts.',
      },
    ],
  },
  {
    id: 'p6_v_re_education',
    paths: ['vanguard'],
    phases: [1, 2],
    weight: 7,
    art: 'bulletin',
    emoji: '🏫',
    title: 'The Re-education Plan',
    body: `A proposal lands on your desk to expand the "re-education" camps in your region — bigger quotas, broader categories of the "unreliable." Your signature would set it moving.`,
    choices: [
      {
        label: 'Sign and expand the program',
        fx: { base: 10, influence: 6, support: -10, heat: 8 },
        inc: { purge_count: 2 },
        set: { bloody_hands: true, tyrant_rep: true },
        tone: 'bold',
        result: 'You sign, and the categories of the doomed widen by a stroke of your pen. The Centre notes your reliability.',
      },
      {
        label: 'Stall it in endless review',
        roll: {
          stat: 'influence',
          dc: 53,
          success: {
            fx: { support: 8, influence: 4, heat: 2 },
            text: 'You bury the plan in committees and "concerns about logistics." It never quite moves. Sabotage by paperwork.',
          },
          fail: {
            fx: { heat: 10, support: -4 },
            text: 'Your stalling is noticed and resented. A note is made about your enthusiasm, or lack of it.',
          },
        },
        set: { secret_reformer: true },
        tone: 'slick',
      },
    ],
  },
  {
    id: 'p6_v_requisition',
    paths: ['vanguard'],
    phases: [1, 2],
    weight: 7,
    art: 'crisis',
    emoji: '🌾',
    title: 'The Grain Requisition',
    body: `The Centre demands a grain quota your farmers cannot meet without going hungry themselves. The order is to take it anyway. The order does not mention the winter.`,
    choices: [
      {
        label: 'Seize the full quota',
        fx: { influence: 8, base: 4, support: -10, heat: 6 },
        set: { bloody_hands: true },
        tone: 'bold',
        result: 'You strip the granaries to the boards. The Centre is satisfied; the villages will remember the cold to come.',
      },
      {
        label: 'Quietly under-report and leave seed grain',
        roll: {
          stat: 'influence',
          dc: 52,
          success: {
            fx: { support: 12, base: 4, influence: -2 },
            text: 'You cook the figures to leave the farmers enough to survive. A dangerous mercy, well hidden.',
          },
          fail: {
            fx: { heat: 12, support: -4 },
            text: 'An inspector finds the gap between your books and your barns. The discrepancy now has your name on it.',
          },
        },
        set: { secret_reformer: true },
        tone: 'good',
      },
    ],
  },
  {
    id: 'p6_v_general',
    paths: ['vanguard'],
    phases: [2, 3],
    weight: 8,
    art: 'rival',
    emoji: '🎖️',
    title: 'The General’s Offer',
    speaker: (S) => ({ name: S.opp, role: 'an army commander', avatar: S.oppAvatar }),
    body: (S) =>
      `${S.opp}, who commands real soldiers, offers you his loyalty — or, between the lines, something more drastic against the Centre if you would only nod.`,
    choices: [
      {
        label: 'Accept his loyalty, refuse the coup',
        fx: { influence: 10, base: 6, heat: 4 },
        set: { has_network: true },
        npcFx: { id: 'antagonist', relationship: 16 },
        tone: 'slick',
        result: 'You take the friendship and decline the treason. A general in your debt is worth more alive than mutinous.',
      },
      {
        label: 'Report his disloyal hint upward',
        fx: { base: 8, influence: 6, heat: 6 },
        inc: { purge_count: 1 },
        npcFx: { id: 'antagonist', relationship: -18 },
        tone: 'bold',
        result: 'You turn the general in before he turns. The Centre rewards your vigilance; the officer corps notes your teeth.',
      },
    ],
  },
  {
    id: 'p6_v_poet',
    paths: ['vanguard'],
    phases: [2, 3],
    weight: 7,
    art: 'scene',
    emoji: '🖋️',
    title: 'The Dissident Poet',
    body: `A beloved poet has written verses the censors call treason and the people call true. The decision of what to do with them — exile, prison, or a quiet pardon — is yours.`,
    choices: [
      {
        label: 'Arrange a quiet exile abroad',
        fx: { support: 8, base: -2, heat: 6 },
        set: { secret_reformer: true },
        tone: 'good',
        result: 'You put the poet on a train to a softer country. They live, they write, and they remember who let them go.',
      },
      {
        label: 'Make a harsh example',
        fx: { base: 10, influence: 4, support: -10 },
        inc: { purge_count: 1 },
        set: { bloody_hands: true, zealot_rep: true },
        tone: 'bold',
        result: 'You jail the poet and the verses spread twice as fast. Martyrs, it turns out, rhyme better.',
      },
    ],
  },

  // ---------------- SHARED ----------------
  {
    id: 'p6_s_intl_prize',
    paths: ['ballot', 'vanguard'],
    phases: [3],
    weight: 7,
    art: 'newspaper',
    emoji: '🏆',
    title: 'The International Prize',
    body: `A prestigious foreign committee wants to award you a peace prize for a deal you cut. Accepting flatters your vanity; it also hands your domestic rivals a "globalist" cudgel.`,
    choices: [
      {
        label: 'Accept it proudly abroad',
        fx: { media: 10, influence: 6, base: -4 },
        tone: 'slick',
        result: 'You give a gracious speech in a far-off hall. The medal gleams; the home crowd grumbles about your passport.',
      },
      {
        label: 'Decline graciously, stay home',
        fx: { base: 8, support: 4 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You turn it down with thanks, citing work undone. Humility plays better in the provinces than any medal.',
      },
    ],
  },
  {
    id: 'p6_s_age_question',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 6,
    art: 'scene',
    emoji: '⏳',
    title: 'The Question of Age',
    body: `Whispers about your stamina have hardened into open commentary. A grueling public test of vigor could silence them — or, if you stumble, confirm them on live television.`,
    choices: [
      {
        label: 'Stage a feat of energy and stamina',
        roll: {
          stat: 'base',
          dc: 52,
          success: {
            fx: { base: 8, media: 8, support: 6 },
            text: 'You out-pace aides half your age for the cameras. The age question dies of embarrassment.',
          },
          fail: {
            fx: { support: -8, media: -4 },
            text: 'You gas out on camera and grab a railing. The clip is captioned cruelly and runs for a week.',
          },
        },
        tone: 'bold',
      },
      {
        label: 'Reframe age as experience',
        fx: { influence: 6, support: 4 },
        tone: 'good',
        result: 'You lean into the grey hair as a feature, not a bug. Wisdom is a slower sell, but a sturdier one.',
      },
    ],
  },
  {
    id: 'p6_s_loyal_aide',
    paths: ['ballot', 'vanguard'],
    phases: [1, 2, 3],
    weight: 6,
    art: 'scene',
    emoji: '🤲',
    title: 'The Aide’s Plea',
    body: `Your most loyal aide — the one who has bled for you for years — quietly asks you to bend a rule to save their drowning sibling. They have never asked you for anything.`,
    choices: [
      {
        label: 'Bend the rule, quietly',
        fx: { base: 6, heat: 8, support: -2 },
        set: { loyal_to_old_friends: true, corrupt_streak: true },
        tone: 'good',
        result: 'You make the call you should not make, for the one person who earned it. Loyalty has a price and you pay it.',
      },
      {
        label: 'Refuse, and explain why',
        fx: { influence: 4, base: -4, support: 4 },
        set: { clean_streak: true },
        tone: 'bold',
        result: 'You say no to the person who deserves a yes. Principle is coldest when it costs a friend.',
      },
    ],
  },
  {
    id: 'p6_s_rival_dies',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 6,
    art: 'rival',
    emoji: '🕯️',
    title: 'The Rival’s Funeral',
    speaker: (S) => ({ name: S.opp, role: 'your late adversary', avatar: S.oppAvatar }),
    body: (S) =>
      `${S.opp}, who fought you for years, has died suddenly. The nation watches to see whether you eulogize an enemy with grace or settle the score from the graveside.`,
    choices: [
      {
        label: 'Deliver a generous eulogy',
        fx: { support: 10, media: 6, base: 2 },
        npcFx: { id: 'antagonist', relationship: 20 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You honor the fight and the fighter. Grace toward a dead rival is the most powerful kind of strength.',
      },
      {
        label: 'Damn them with faint praise',
        fx: { base: 4, heat: 6, support: -6 },
        tone: 'slick',
        result: 'You manage a few cold words and a colder smile. The pettiness, at a funeral, is what people remember.',
      },
    ],
  },
  {
    id: 'p6_s_data_leak',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 6,
    art: 'newspaper',
    emoji: '🔓',
    title: 'The Private Files',
    body: `Your private messages — unguarded, human, occasionally damning — have been hacked and are trickling out. Damage control now decides which version of you the public meets.`,
    choices: [
      {
        label: 'Get ahead of it; release them yourself',
        roll: {
          stat: 'media',
          dc: 52,
          success: {
            fx: { media: 8, support: 6, heat: -4 },
            text: 'You publish the lot first and frame it as transparency. Owning the story strips the leak of its power.',
          },
          fail: {
            fx: { support: -8, heat: 8 },
            text: 'The "transparency" gambit only spotlights the worst lines. You handed them the highlight reel.',
          },
        },
        tone: 'bold',
      },
      {
        label: 'Deny, delay, and lawyer up',
        fx: { heat: 8, influence: 4, support: -4 },
        set: { stonewaller: true },
        tone: 'slick',
        result: 'You contest authenticity and run out the clock. It half-works, and the doubt clings to you like smoke.',
      },
    ],
  },
  {
    id: 'p6_s_protege_returns',
    paths: ['ballot', 'vanguard'],
    phases: [3],
    weight: 6,
    art: 'rival',
    emoji: '🐍',
    title: 'The Protégé’s Ambition',
    body: `The bright deputy you once mentored now eyes your chair openly. They have learned everything you taught them, including the part about not waiting your turn.`,
    choices: [
      {
        label: 'Bring them closer; co-opt the threat',
        fx: { influence: 8, base: 4, heat: 4 },
        set: { has_network: true },
        tone: 'slick',
        result: 'You promote them into a golden cage of responsibility. Better an heir in your sight than a rival at your back.',
      },
      {
        label: 'Clip their wings decisively',
        fx: { base: 8, influence: 4, support: -4, heat: 6 },
        tone: 'bold',
        result: 'You sideline the upstart before they bloom. The lesson you taught them about ruthlessness, they take to heart.',
      },
    ],
  },

  // ---------------- CRISES ----------------
  {
    id: 'p6_c_drought',
    paths: ['ballot', 'vanguard'],
    phases: [1, 2, 3],
    weight: 8,
    crisis: true,
    art: 'crisis',
    emoji: '🏜️',
    title: 'The Long Drought',
    body: `Reservoirs are mudflats and the crops are curling brown. You can ration water fairly across the country or quietly favor the regions that vote — or fear — the right way.`,
    choices: [
      {
        label: 'Ration fairly, everywhere',
        fx: { support: 12, base: 4, influence: -2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You share the thirst evenly and explain why. Fairness in scarcity is the hardest, most respected kind.',
      },
      {
        label: 'Steer the water toward your strongholds',
        fx: { base: 8, influence: 4, support: -8, heat: 6 },
        scandal: { id: 'water_favor', label: 'the water you steered to friends', severity: 2 },
        tone: 'slick',
        result: 'Your loyal regions stay green while others crack. Useful, and exactly the sort of map that gets published later.',
      },
    ],
  },
  {
    id: 'p6_c_coup',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 9,
    crisis: true,
    art: 'crisis',
    emoji: '🪖',
    title: 'The Coup Attempt',
    body: `At dawn, units you do not control seize the broadcast tower and the bridges. The next few hours decide whether you are a leader or a footnote. The cameras, somewhere, are still on.`,
    choices: [
      {
        label: 'Go to the people; rally the streets',
        roll: {
          stat: 'support',
          dc: 53,
          success: {
            fx: { support: 16, base: 10, influence: 6 },
            text: 'You appear unguarded among the crowds and they surge to your side. The coup dissolves against a wall of people.',
          },
          fail: {
            fx: { support: -10, heat: 12 },
            text: 'You gamble on the streets and the streets hesitate. The standoff teeters on a knife you cannot see.',
          },
        },
        set: { peacemaker: true },
        tone: 'bold',
      },
      {
        label: 'Crush it with loyal force',
        fx: { base: 10, influence: 8, heat: 14, support: -4 },
        inc: { purge_count: 2 },
        set: { bloody_hands: true, tyrant_rep: true },
        tone: 'bold',
        result: 'Your loyal units retake the bridges by force. You survive, hardened and bloodied, and the purge that follows is thorough.',
      },
    ],
  },
  {
    id: 'p6_c_hostage',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 8,
    crisis: true,
    art: 'crisis',
    emoji: '🔫',
    title: 'The Hostage Crisis',
    body: `Gunmen have seized a school full of children and a building full of cameras. Their demands are impossible, the clock is loud, and every option ends with someone’s name on it.`,
    choices: [
      {
        label: 'Negotiate patiently for the children',
        roll: {
          stat: 'support',
          dc: 54,
          success: {
            fx: { support: 14, influence: 6 },
            text: 'You keep the line open for grueling hours and the children walk out alive. Patience, this time, saved them.',
          },
          fail: {
            fx: { support: -8, heat: 8 },
            text: 'The talks collapse and the ending is partial and grim. You will replay every hour of it for years.',
          },
        },
        tone: 'good',
      },
      {
        label: 'Order an immediate assault',
        fx: { base: 8, heat: 12, support: -4 },
        tone: 'bold',
        result: 'You send the teams in fast and hard. It ends in minutes, decisively, and the cost of those minutes is yours to carry.',
      },
    ],
  },
  {
    id: 'p6_c_flood',
    paths: ['ballot', 'vanguard'],
    phases: [1, 2, 3],
    weight: 8,
    crisis: true,
    art: 'crisis',
    emoji: '🌧️',
    title: 'The Great Flood',
    body: `The river has jumped its banks and swallowed half a province. To save the cities downstream, the engineers can breach a levee — and deliberately drown a hundred farms upstream.`,
    choices: [
      {
        label: 'Breach the levee; sacrifice the farms',
        roll: {
          stat: 'influence',
          dc: 52,
          success: {
            fx: { influence: 8, support: 6, funds: -6 },
            text: 'You make the brutal call and the cities hold. You also compensate the farmers fast, which is the only thing that makes it survivable.',
          },
          fail: {
            fx: { support: -10, heat: 8 },
            text: 'You drown the farms and the cities flood anyway. The worst of both choices, and all of the blame.',
          },
        },
        tone: 'bold',
      },
      {
        label: 'Refuse; fight to save everyone',
        fx: { support: 8, funds: -10, heat: 6 },
        tone: 'good',
        result: 'You throw everything at saving both and pray the sandbags hold. A gamble of conscience, paid in exhaustion and treasure.',
      },
    ],
  },
  {
    id: 'p6_c_pandemic_wave',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 8,
    crisis: true,
    art: 'crisis',
    emoji: '💉',
    title: 'The Second Wave',
    body: `The sickness is back and a vaccine exists, but there is only enough for some. Who gets it first — the vulnerable, the essential, or the loyal — is a decision history will read closely.`,
    choices: [
      {
        label: 'Prioritize the vulnerable and essential',
        fx: { support: 12, base: 4, influence: 4 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You give the first doses to the old, the sick, and the carers. The fairness is quiet, costly, and right.',
      },
      {
        label: 'Reward the loyal and the useful first',
        fx: { base: 8, influence: 6, support: -8, heat: 6 },
        scandal: { id: 'vaccine_favor', label: 'the doses you handed to loyalists', severity: 2 },
        tone: 'slick',
        result: 'The well-connected roll up their sleeves first. A list exists of who got it early, and lists like that surface.',
      },
    ],
  },
];
