import type { GameEvent } from '../engine/types';

/**
 * Content pack 9 — ninth volume expansion; the one that carries the bank past
 * the 250-event target. Dynasties, concessions, and make-or-break primaries
 * (ballot); named successions, reversed purges, and the resistant old guard
 * (vanguard); legacy-building, term limits, and the temptation to walk away
 * (shared); and six new crises. Fictional and non-partisan by construction.
 */
export const PACK_9: GameEvent[] = [
  // ---------------- BALLOT ----------------
  {
    id: 'p9_b_dynasty',
    paths: ['ballot'],
    phases: [3],
    weight: 6,
    art: 'scene',
    emoji: '👨‍👧',
    title: 'The Dynasty Question',
    body: `Your talented child wants to enter politics in your shadow, riding your name to a head start they did not earn. Build a dynasty, or make them earn their own way.`,
    choices: [
      {
        label: 'Clear the path for them',
        fx: { influence: 8, base: 4, heat: 6, support: -4 },
        set: { nepotism: true },
        tone: 'slick',
        result: 'You hand your heir a launchpad. The name opens every door, and the word "dynasty" follows them like a shadow.',
      },
      {
        label: 'Make them start at the bottom',
        fx: { support: 8, base: 2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You refuse to gift them the climb. They resent it now and will thank you, or not, much later.',
      },
    ],
  },
  {
    id: 'p9_b_concession',
    paths: ['ballot'],
    phases: [3],
    weight: 8,
    art: 'newspaper',
    emoji: '🤝',
    title: 'The Close Loss',
    body: `The count is in and you have lost — narrowly, painfully, but really. You can concede with grace, or contest the margin and keep the wound open.`,
    choices: [
      {
        label: 'Concede graciously',
        fx: { support: 10, base: 4, media: 6 },
        set: { honest_rep: true, peacemaker: true },
        tone: 'good',
        result: 'You congratulate the winner and thank your people. A dignified loss is its own kind of victory, bankable later.',
      },
      {
        label: 'Contest every ballot',
        fx: { base: 8, heat: 12, support: -8 },
        scandal: { id: 'contested_loss', label: 'the loss you refused to accept', severity: 2 },
        tone: 'bold',
        result: 'You fight the result through every court and rally. The base stays fervent; the country grows wearier of you.',
      },
    ],
  },
  {
    id: 'p9_b_tragedy',
    paths: ['ballot'],
    phases: [2, 3],
    weight: 7,
    art: 'crisis',
    emoji: '🕯️',
    title: 'The Tragedy on the News',
    body: `A horrific event has the whole nation grieving, and your strategists see an opening to score a sharp political point while emotions run hot.`,
    choices: [
      {
        label: 'Just grieve with the country',
        fx: { support: 10, base: 2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You set politics down for a day and simply mourn alongside everyone. The restraint is noticed and respected.',
      },
      {
        label: 'Score the point while it’s raw',
        roll: {
          stat: 'media',
          dc: 54,
          success: {
            fx: { base: 8, media: 4 },
            text: 'You thread the needle and land the argument without looking ghoulish. Barely.',
          },
          fail: {
            fx: { support: -12, heat: 6 },
            text: 'You look like you’re dancing on grief. The clip of it haunts you for the rest of the cycle.',
          },
        },
        tone: 'slick',
      },
    ],
  },
  {
    id: 'p9_b_grassroots_surge',
    paths: ['ballot'],
    phases: [1, 2],
    weight: 6,
    art: 'scene',
    emoji: '📲',
    title: 'The Small-Dollar Surge',
    body: `A heartfelt moment of yours has gone viral and small donations are flooding in from ordinary people. It is real, grassroots momentum — and a lot to live up to.`,
    choices: [
      {
        label: 'Lean fully into the people-powered story',
        fx: { base: 10, support: 8, funds: 6 },
        set: { grassroots: true },
        tone: 'good',
        result: 'You build the whole campaign around the surge. The energy is genuine and the expectations are now enormous.',
      },
      {
        label: 'Bank it quietly and stay disciplined',
        fx: { funds: 10, base: 2 },
        tone: 'slick',
        result: 'You take the money without overpromising. Less romance, more runway.',
      },
    ],
  },
  {
    id: 'p9_b_fringe_endorse',
    paths: ['ballot'],
    phases: [2, 3],
    weight: 6,
    art: 'newspaper',
    emoji: '📛',
    title: 'The Unwanted Endorsement',
    body: `A genuinely ugly fringe group has loudly endorsed you, delighted. Their voters are real; their reputation is poison. Your rivals are already screenshotting.`,
    choices: [
      {
        label: 'Denounce them unequivocally',
        fx: { support: 8, base: -4, media: 4 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You reject the endorsement in the plainest possible terms. You lose a few votes and keep your soul on the record.',
      },
      {
        label: 'Stay silent and keep their votes',
        fx: { base: 6, heat: 8, support: -6 },
        set: { tyrant_rep: true },
        tone: 'slick',
        result: 'You say nothing and pocket the bloc. The silence is loud, and the screenshots are forever.',
      },
    ],
  },
  {
    id: 'p9_b_admit_wrong',
    paths: ['ballot'],
    phases: [1, 2, 3],
    weight: 6,
    art: 'scene',
    emoji: '🙋',
    title: 'The Honest Question',
    body: `At a town hall, a voter calmly asks you to admit that a past position of yours was simply wrong. The room leans in. So do the cameras.`,
    choices: [
      {
        label: 'Admit it, plainly',
        fx: { support: 10, base: 2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You say "you’re right, I was wrong, and here’s what changed my mind." Honesty like that is rare enough to trend.',
      },
      {
        label: 'Defend the old position anyway',
        roll: {
          stat: 'base',
          dc: 50,
          success: {
            fx: { base: 8 },
            text: 'You hold the line with enough conviction that your base cheers the consistency.',
          },
          fail: {
            fx: { support: -8, heat: 2 },
            text: 'The refusal to ever admit error reads as exactly the problem. Stubbornness, on camera, isn’t strength.',
          },
        },
        tone: 'bold',
      },
    ],
  },
  {
    id: 'p9_b_primary_day',
    paths: ['ballot'],
    phases: [1, 2],
    weight: 7,
    art: 'bulletin',
    emoji: '🗳️',
    title: 'The Decisive Primary',
    body: `It all comes down to one enormous primary day. You can blitz everywhere thinly or pour everything into the few contests that actually decide it.`,
    choices: [
      {
        label: 'Concentrate on the must-wins',
        roll: {
          stat: 'base',
          dc: 52,
          success: {
            fx: { base: 12, support: 8 },
            text: 'You win where it counts and the math suddenly tilts your way. Focus beats sprawl.',
          },
          fail: {
            fx: { support: -8, base: -2 },
            text: 'You go all-in on a few and lose two of them. The narrow bet leaves you exposed everywhere else.',
          },
        },
        tone: 'bold',
      },
      {
        label: 'Compete everywhere for the delegate trickle',
        fx: { support: 4, base: 4, funds: -6 },
        tone: 'slick',
        result: 'You spread thin and collect scraps in every state. No knockout, but no collapse either.',
      },
    ],
  },
  {
    id: 'p9_b_celebrity_run',
    paths: ['ballot'],
    phases: [1, 2],
    weight: 6,
    art: 'rival',
    emoji: '🌟',
    title: 'The Celebrity Enters',
    body: `A wildly popular entertainer with no experience has jumped into the race, sucking up all the oxygen and polling absurdly well on pure fame.`,
    choices: [
      {
        label: 'Respect them; contrast on substance',
        fx: { support: 8, influence: 4, base: -2 },
        tone: 'good',
        result: 'You treat them seriously and quietly highlight the gap in depth. Substance is a slow weapon, but it cuts.',
      },
      {
        label: 'Mock the famous amateur',
        roll: {
          stat: 'media',
          dc: 52,
          success: {
            fx: { media: 6, base: 6 },
            text: 'Your jabs at the dilettante land and the shine wears off them fast.',
          },
          fail: {
            fx: { support: -8, media: -2 },
            text: 'Punching at a beloved star makes you the villain. Their fans become their voters out of spite.',
          },
        },
        tone: 'bold',
      },
    ],
  },

  // ---------------- VANGUARD ----------------
  {
    id: 'p9_v_child_informs',
    paths: ['vanguard'],
    phases: [1, 2],
    weight: 7,
    art: 'bulletin',
    emoji: '🧒',
    title: 'The Child’s Report',
    body: `A young pioneer has dutifully informed on their own parent for "unreliable talk." The system wants you to reward the child and arrest the parent. The child is eight.`,
    choices: [
      {
        label: 'Quietly bury the report',
        fx: { support: 10, base: -4, heat: 8 },
        set: { secret_reformer: true, honest_rep: true },
        tone: 'good',
        result: 'You misplace the denunciation and send the child home with a sweet and a warning. A family survives your mercy.',
      },
      {
        label: 'Reward the child, arrest the parent',
        fx: { base: 10, influence: 4, support: -10 },
        inc: { purge_count: 1 },
        set: { bloody_hands: true, zealot_rep: true },
        tone: 'bold',
        result: 'You pin a medal on the child and lead the parent away. The system is fed; something in the room dies quietly.',
      },
    ],
  },
  {
    id: 'p9_v_named_heir',
    paths: ['vanguard'],
    phases: [3],
    weight: 9,
    art: 'bulletin',
    emoji: '👑',
    title: 'The Poisoned Chalice',
    body: `The dying leader has, at last, named you successor — which paints a target on your back the size of the republic. Every rival now has one goal, and it is you.`,
    choices: [
      {
        label: 'Consolidate fast and ruthlessly',
        fx: { influence: 10, base: 8, heat: 10, support: -4 },
        inc: { purge_count: 1 },
        set: { has_network: true, bloody_hands: true },
        tone: 'bold',
        result: 'You move before your rivals can, locking down the levers overnight. Power secured, in blood and paperwork.',
      },
      {
        label: 'Build a broad coalition to protect the throne',
        fx: { influence: 8, support: 8, base: -2 },
        set: { has_network: true, peacemaker: true },
        tone: 'slick',
        result: 'You buy loyalty with posts and promises instead of fear. Slower, softer, and far harder to stab in the back.',
      },
    ],
  },
  {
    id: 'p9_v_reverse_purge',
    paths: ['vanguard'],
    phases: [2, 3],
    weight: 6,
    art: 'scene',
    emoji: '↩️',
    title: 'The Purge You Regret',
    body: `Someone you helped condemn years ago turns out to have been innocent, and their family is suffering for it still. You could quietly make it right, at some risk to yourself.`,
    choices: [
      {
        label: 'Secretly restore the family',
        fx: { support: 10, influence: -4, heat: 6 },
        set: { secret_reformer: true, honest_rep: true },
        tone: 'good',
        result: 'You arrange a quiet restoration of name and pension. It cannot undo the years, but it is something, paid from your own standing.',
      },
      {
        label: 'Let the old verdict stand',
        fx: { influence: 4, base: 2, heat: -2 },
        tone: 'slick',
        result: 'You decide that reopening it endangers you more than it helps them. The file stays closed; so does that door in you.',
      },
    ],
  },
  {
    id: 'p9_v_slowdown',
    paths: ['vanguard'],
    phases: [1, 2],
    weight: 6,
    art: 'bulletin',
    emoji: '🐢',
    title: 'The Slowdown',
    body: `Workers in your sector are quietly working to rule — not striking, just slowing — to protest impossible quotas. The Centre calls it sabotage and wants names.`,
    choices: [
      {
        label: 'Ease the quotas instead of punishing',
        fx: { support: 10, base: 2, influence: -4 },
        set: { secret_reformer: true },
        tone: 'good',
        result: 'You quietly lower the impossible targets and the work resumes. You call it "efficiency"; the workers call it relief.',
      },
      {
        label: 'Round up the "saboteurs"',
        fx: { base: 8, influence: 4, support: -8 },
        inc: { purge_count: 1 },
        set: { bloody_hands: true },
        tone: 'bold',
        result: 'You give the Centre its names. The slowdown ends in fear, and the quotas remain as impossible as ever.',
      },
    ],
  },
  {
    id: 'p9_v_foreign_press',
    paths: ['vanguard'],
    phases: [2, 3],
    weight: 6,
    art: 'rival',
    emoji: '📰',
    title: 'The Foreign Interview',
    body: `A sharp foreign journalist has been granted a rare interview and is circling the questions you most want to avoid. Every answer will be quoted in two languages.`,
    choices: [
      {
        label: 'Answer with surprising candor',
        roll: {
          stat: 'media',
          dc: 54,
          success: {
            fx: { media: 10, support: 8, influence: 4 },
            text: 'You disarm them with unexpected honesty and come off as a reformer the world can deal with. A coup, abroad and at home.',
          },
          fail: {
            fx: { heat: 10, base: -4 },
            text: 'Your candor is quoted out of context and the hardliners at home smell deviation. Honesty has costs here.',
          },
        },
        set: { secret_reformer: true },
        tone: 'bold',
      },
      {
        label: 'Stonewall with slogans',
        fx: { base: 6, media: -2, heat: 2 },
        tone: 'slick',
        result: 'You answer every question with the same three approved phrases. Safe, wooden, and utterly unconvincing.',
      },
    ],
  },
  {
    id: 'p9_v_old_guard',
    paths: ['vanguard'],
    phases: [2, 3],
    weight: 7,
    art: 'scene',
    emoji: '🧓',
    title: 'The Old Guard',
    body: `The aging hardliners who run the apparatus are quietly strangling your every modest reform. You can purge them, outwait them, or abandon the reforms to keep the peace.`,
    choices: [
      {
        label: 'Outmaneuver them patiently',
        fx: { influence: 8, support: 6, base: -2 },
        set: { secret_reformer: true, has_network: true },
        tone: 'slick',
        result: 'You promote around them and wait for time to do your purging for you. Patience, here, is the gentlest blade.',
      },
      {
        label: 'Purge the obstructers',
        fx: { base: 8, influence: 6, heat: 8, support: -6 },
        inc: { purge_count: 2 },
        set: { bloody_hands: true },
        tone: 'bold',
        result: 'You clear the old men out in a single hard season. The reforms move; so does a chill through every office.',
      },
    ],
  },
  {
    id: 'p9_v_statue_toppled',
    paths: ['vanguard'],
    phases: [3],
    weight: 7,
    art: 'crisis',
    emoji: '🗿',
    title: 'They Toppled Your Statue',
    body: `In a distant city, a crowd has pulled down a statue of you and dragged it through the square. It is small, it is contained — and it is the first time the fear has cracked.`,
    choices: [
      {
        label: 'Respond with reform, not reprisal',
        roll: {
          stat: 'support',
          dc: 54,
          success: {
            fx: { support: 12, base: 4, heat: -4 },
            text: 'You answer the toppling with genuine concessions, and the crack closes instead of spreading. Rare wisdom under fire.',
          },
          fail: {
            fx: { support: -6, heat: 8 },
            text: 'Your softness is read as weakness and a second statue falls the next week. Mercy mistimed invites more.',
          },
        },
        set: { peacemaker: true },
        tone: 'good',
      },
      {
        label: 'Crush the city as a warning',
        fx: { base: 8, heat: 16, support: -12 },
        inc: { purge_count: 2 },
        set: { bloody_hands: true, tyrant_rep: true },
        tone: 'bold',
        result: 'You make the city pay so the others won’t dare. The statues stand again, polished by fear, and the fear remembers.',
      },
    ],
  },
  {
    id: 'p9_v_famous_prisoner',
    paths: ['vanguard'],
    phases: [2, 3],
    weight: 6,
    art: 'scene',
    emoji: '🔑',
    title: 'The Famous Prisoner',
    body: `The world’s most famous political prisoner sits in your custody, and foreign powers are dangling real rewards for their release. Mercy, leverage, or a stubborn show of strength.`,
    choices: [
      {
        label: 'Release them for genuine concessions',
        fx: { influence: 8, support: 8, base: -4 },
        set: { dealmaker: true, peacemaker: true },
        tone: 'good',
        result: 'You trade the prisoner for real gains and global goodwill. The hardliners grumble; the ledger and the world approve.',
      },
      {
        label: 'Keep them as a permanent symbol',
        fx: { base: 8, heat: 8, support: -6 },
        set: { tyrant_rep: true },
        tone: 'bold',
        result: 'You keep the famous captive caged as a trophy of your resolve. The world keeps their face on its posters.',
      },
    ],
  },

  // ---------------- SHARED ----------------
  {
    id: 'p9_s_term_limit',
    paths: ['ballot', 'vanguard'],
    phases: [3],
    weight: 8,
    art: 'bulletin',
    emoji: '⏰',
    title: 'The Term Limit',
    body: `Your time is supposed to be ending, but allies are urging you to change the rules and stay. Power is sweet, the work feels unfinished, and the door is right there.`,
    choices: [
      {
        label: 'Honor the limit; step aside on time',
        fx: { support: 12, base: -2, media: 6 },
        set: { honest_rep: true, peacemaker: true },
        tone: 'good',
        result: 'You walk away while you still could have stayed. Letting go of power willingly is the rarest move in the game.',
      },
      {
        label: 'Change the rules and stay',
        fx: { influence: 10, base: 6, heat: 12, support: -8 },
        set: { own_cult: true, tyrant_rep: true },
        scandal: { id: 'rules_changed', label: 'the term limit you erased', severity: 3 },
        tone: 'bold',
        result: 'You rewrite the calendar to keep the chair. The applause is loud; the precedent is a door that never closes again.',
      },
    ],
  },
  {
    id: 'p9_s_legacy_library',
    paths: ['ballot', 'vanguard'],
    phases: [3],
    weight: 6,
    art: 'scene',
    emoji: '🏛️',
    title: 'The Legacy Project',
    body: `Aides want to break ground on a grand monument to your era — a library, an institute, a temple to your record. It could inspire, or it could read as a pharaoh’s tomb.`,
    choices: [
      {
        label: 'Build something genuinely useful and modest',
        fx: { support: 8, funds: -4, base: 2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You fund schools and clinics with your name on a small plaque. The legacy is in the using, not the gazing.',
      },
      {
        label: 'Build the grand monument to yourself',
        fx: { media: 8, base: 6, funds: -8, heat: 4 },
        set: { cult_building: true },
        tone: 'slick',
        result: 'The marble rises, vast and gleaming and a little funereal. History will admire it or smirk at it; you won’t be there to know which.',
      },
    ],
  },
  {
    id: 'p9_s_apology',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 6,
    art: 'newspaper',
    emoji: '🙏',
    title: 'The Reckoning',
    body: `Pressure is building to formally apologize for a historic wrong your office committed long before you. An apology heals and admits; silence protects and denies.`,
    choices: [
      {
        label: 'Offer a full, sincere apology',
        fx: { support: 10, base: -2, media: 4 },
        set: { honest_rep: true, peacemaker: true },
        tone: 'good',
        result: 'You name the old wrong and ask forgiveness without hedging. The gesture costs you a wing and earns you a country.',
      },
      {
        label: 'Refuse to "apologize for history"',
        fx: { base: 8, heat: 4, support: -6 },
        tone: 'bold',
        result: 'You decline to kneel for the past. Your base calls it backbone; the wronged call it the wound, still open.',
      },
    ],
  },
  {
    id: 'p9_s_surprise_alliance',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 6,
    art: 'rival',
    emoji: '🫱',
    title: 'The Unlikely Alliance',
    speaker: (S) => ({ name: S.opp, role: 'an old enemy', avatar: S.oppAvatar }),
    body: (S) =>
      `${S.opp}, your bitterest rival, proposes a startling alliance against a greater common threat. The logic is sound; the trust is nonexistent.`,
    choices: [
      {
        label: 'Take the alliance, eyes open',
        fx: { influence: 10, base: 4, heat: 4 },
        npcFx: { id: 'antagonist', relationship: 16 },
        set: { dealmaker: true },
        tone: 'slick',
        result: 'You shake the hand of your enemy against a worse one. Strange bedfellows, watchful sleep.',
      },
      {
        label: 'Refuse; trust no one',
        fx: { base: 6, support: -2, heat: 2 },
        npcFx: { id: 'antagonist', relationship: -8 },
        tone: 'bold',
        result: 'You turn the offer down flat. You face the greater threat alone, with your distrust intact and useless.',
      },
    ],
  },
  {
    id: 'p9_s_groom_successor',
    paths: ['ballot', 'vanguard'],
    phases: [3],
    weight: 6,
    art: 'scene',
    emoji: '🌿',
    title: 'Choosing an Heir',
    body: `You will not rule forever, and the question of who comes after is suddenly real. A loyal mediocrity who will protect your legacy, or a brilliant independent who might surpass it?`,
    choices: [
      {
        label: 'Anoint the brilliant independent',
        fx: { support: 8, influence: 4, base: -2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You back the one who might outshine you. The country wins; your monuments may not get dusted.',
      },
      {
        label: 'Anoint the loyal protector',
        fx: { influence: 6, base: 6, heat: 2 },
        set: { has_network: true },
        tone: 'slick',
        result: 'You choose the one who will guard your record above all. Your legacy is safe; the future is slightly smaller.',
      },
    ],
  },
  {
    id: 'p9_s_press_clampdown',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 6,
    art: 'newspaper',
    emoji: '📵',
    title: 'The Troublesome Press',
    body: `A relentless outlet keeps publishing things that are true and damaging. You have the means to make their life very hard — licenses, audits, access. The temptation is real.`,
    choices: [
      {
        label: 'Leave the press alone, however it stings',
        fx: { support: 8, base: -2, heat: -4 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You resist the urge to punish honest reporting. A free press that bites you is the price of not being a tyrant.',
      },
      {
        label: 'Squeeze them quietly',
        fx: { base: 4, heat: 10, support: -6 },
        inc: { purge_count: 1 },
        set: { tyrant_rep: true },
        scandal: { id: 'press_squeeze', label: 'the outlet you strangled', severity: 2 },
        tone: 'slick',
        result: 'Their licenses get complicated and their access dries up. The reporting softens, and so does any claim you’re a democrat.',
      },
    ],
  },
  {
    id: 'p9_s_family_threat',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 6,
    art: 'crisis',
    emoji: '🛡️',
    title: 'The Threat to Family',
    body: `A credible, specific threat has been made against your family. You can lock them away in safety and out of public life, or refuse to let fear dictate how you live.`,
    choices: [
      {
        label: 'Refuse to be ruled by fear',
        roll: {
          stat: 'base',
          dc: 52,
          success: {
            fx: { support: 10, base: 6 },
            text: 'You harden security quietly but live openly, and the defiance steadies the whole country’s nerve.',
          },
          fail: {
            fx: { support: -6, heat: 6 },
            text: 'The bravado looks reckless when a scare gets close. "Why risk them?" becomes the question.',
          },
        },
        tone: 'bold',
      },
      {
        label: 'Lock them away in safety',
        fx: { heat: -6, influence: 2, support: -2 },
        tone: 'good',
        result: 'You wrap your family in armor and shadow. They are safe, and a little lost to you, and that is the trade.',
      },
    ],
  },
  {
    id: 'p9_s_walk_away',
    paths: ['ballot', 'vanguard'],
    phases: [3],
    weight: 6,
    art: 'scene',
    emoji: '🚪',
    title: 'The Open Door',
    body: `Exhausted to the bone, you catch yourself daydreaming of simply walking away — a quiet life, a clear conscience, a door standing open. The work is endless; you are not.`,
    choices: [
      {
        label: 'Recommit; there is more to finish',
        fx: { base: 8, support: 4, heat: 2 },
        tone: 'bold',
        result: 'You square your shoulders and stay in the arena. The fire is banked but not out; the work pulls you back in.',
      },
      {
        label: 'Quietly plan your graceful exit',
        fx: { support: 8, base: -4 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You start arranging an ending on your own terms. Knowing when to leave is a wisdom most in this game never learn.',
      },
    ],
  },

  // ---------------- CRISES ----------------
  {
    id: 'p9_c_neighbor_aid',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 8,
    crisis: true,
    art: 'crisis',
    emoji: '🤲',
    title: 'The Neighbor’s Plea',
    body: `A neighboring nation is drowning in catastrophe and begs your help — but your own people are stretched thin, and generosity abroad is a hard sell at home.`,
    choices: [
      {
        label: 'Send real, generous aid',
        fx: { influence: 8, support: 6, funds: -10 },
        set: { peacemaker: true },
        tone: 'good',
        result: 'You open the warehouses for a neighbor in need. It costs you at home and buys you something rarer: gratitude between nations.',
      },
      {
        label: 'Look after your own first',
        fx: { base: 8, support: 4, influence: -4 },
        tone: 'bold',
        result: 'You keep the aid at home and let the neighbor fend for itself. Defensible, popular, and not soon forgotten next door.',
      },
    ],
  },
  {
    id: 'p9_c_outbreak_origin',
    paths: ['ballot', 'vanguard'],
    phases: [1, 2, 3],
    weight: 8,
    crisis: true,
    art: 'crisis',
    emoji: '🧫',
    title: 'The Source',
    body: `A dangerous outbreak has started, and the evidence points to a facility under your own authority. You can be transparent about the origin or quietly point the finger elsewhere.`,
    choices: [
      {
        label: 'Disclose the origin honestly',
        fx: { support: 10, influence: -2, heat: -4 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You admit where it began and focus everyone on the fix. The candor costs you, and contains the thing faster.',
      },
      {
        label: 'Pin it on a foreign source',
        roll: {
          stat: 'media',
          dc: 54,
          success: {
            fx: { base: 8, media: 4 },
            text: 'The misdirection holds and the blame drifts safely abroad. For now.',
          },
          fail: {
            fx: { support: -12, heat: 12 },
            text: 'The real origin leaks with your cover story attached. The lie eclipses the outbreak.',
          },
        },
        scandal: { id: 'outbreak_lie', label: 'the outbreak origin you hid', severity: 3 },
        tone: 'slick',
      },
    ],
  },
  {
    id: 'p9_c_grid_sabotage',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 8,
    crisis: true,
    art: 'crisis',
    emoji: '🧨',
    title: 'The Sabotage',
    body: `Someone has deliberately blown a key piece of infrastructure, and the country is dark and frightened. You can investigate carefully or seize the moment to crush convenient enemies.`,
    choices: [
      {
        label: 'Investigate carefully, lead the repair',
        roll: {
          stat: 'influence',
          dc: 52,
          success: {
            fx: { influence: 10, support: 8 },
            text: 'You find the real culprits and restore the lights without a witch-hunt. Calm competence, rewarded.',
          },
          fail: {
            fx: { support: -6, heat: 6 },
            text: 'The patient approach looks slow to a frightened public that wanted heads on pikes by morning.',
          },
        },
        tone: 'good',
      },
      {
        label: 'Blame your enemies, round them up',
        fx: { base: 10, heat: 12, support: -6 },
        inc: { purge_count: 2 },
        set: { bloody_hands: true, tyrant_rep: true },
        tone: 'bold',
        result: 'You name the usual suspects and sweep them up before the evidence does. The lights come back on over full jails.',
      },
    ],
  },
  {
    id: 'p9_c_currency_attack',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 8,
    crisis: true,
    art: 'crisis',
    emoji: '📉',
    title: 'The Speculators’ Raid',
    body: `Foreign speculators are betting fortunes against your currency, and it is sliding toward freefall. You can burn the reserves to defend it or let it float and absorb the shock.`,
    choices: [
      {
        label: 'Defend the currency with the reserves',
        roll: {
          stat: 'influence',
          dc: 53,
          success: {
            fx: { influence: 10, support: 6, funds: -8 },
            text: 'You spend big and break the speculators’ nerve. The currency holds and the raiders slink off with losses.',
          },
          fail: {
            fx: { funds: -10, support: -8, heat: 6 },
            text: 'You burn the reserves and the speculators win anyway. Now you’re poorer and the currency still fell.',
          },
        },
        tone: 'bold',
      },
      {
        label: 'Let it float, cushion the people',
        fx: { support: 6, funds: -4, base: 2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You let the currency find its level and spend on softening the blow for ordinary households. Painful, honest, survivable.',
      },
    ],
  },
  {
    id: 'p9_c_heatwave',
    paths: ['ballot', 'vanguard'],
    phases: [1, 2, 3],
    weight: 8,
    crisis: true,
    art: 'crisis',
    emoji: '🌡️',
    title: 'The Killing Heat',
    body: `A record heatwave is killing the old and the poor in their homes, and the power grid is straining toward collapse under the load of a million desperate fans.`,
    choices: [
      {
        label: 'Open cooling centers; protect the vulnerable',
        fx: { support: 12, funds: -8, base: 2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You throw open public buildings and check on the isolated. Unglamorous, lifesaving, and quietly heroic.',
      },
      {
        label: 'Protect the grid, ration the power',
        roll: {
          stat: 'influence',
          dc: 52,
          success: {
            fx: { influence: 8, support: 4 },
            text: 'You manage the load and keep the grid alive through the worst of it. The blackout that didn’t happen earns no headlines.',
          },
          fail: {
            fx: { support: -10, heat: 6 },
            text: 'The rationing leaves the wrong neighborhoods sweltering and the toll climbs. The map of who you cut is studied later.',
          },
        },
        tone: 'slick',
      },
    ],
  },
  {
    id: 'p9_c_satellite',
    paths: ['ballot', 'vanguard'],
    phases: [1, 2, 3],
    weight: 7,
    crisis: true,
    art: 'crisis',
    emoji: '🛰️',
    title: 'The Falling Star',
    body: `A defunct satellite is tumbling out of orbit and no one can quite say where it will come down. The public is half-terrified, half-thrilled, and entirely glued to you for reassurance.`,
    choices: [
      {
        label: 'Level with people; share the real odds',
        fx: { support: 10, media: 4 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You explain the actual (tiny) risk plainly and the panic deflates into fascination. Honesty, calmly delivered, is a sedative.',
      },
      {
        label: 'Milk the drama for a rally-round moment',
        roll: {
          stat: 'media',
          dc: 50,
          success: {
            fx: { media: 8, base: 6 },
            text: 'You turn the falling star into a flag-waving spectacle of national resolve. It lands harmlessly; you look commanding.',
          },
          fail: {
            fx: { support: -6, heat: 4 },
            text: 'The hype curdles when people realize you oversold a near-zero risk. Crying wolf at the sky has a cost.',
          },
        },
        tone: 'slick',
      },
    ],
  },
];
