import type { GameEvent } from '../engine/types';

/**
 * Content pack 5 — fifth volume expansion. Redistricting and policy votes on the
 * ballot side; purge quotas, samizdat, and committee knife-fights on the
 * vanguard side; documentaries and anniversaries shared; and five new crises
 * (refugees, terror, bank run, wildfire, chemical spill). Fictional and
 * non-partisan by construction.
 */
export const PACK_5: GameEvent[] = [
  // ---------------- BALLOT ----------------
  {
    id: 'p5_b_gerrymander',
    paths: ['ballot'],
    phases: [2, 3],
    weight: 7,
    art: 'newspaper',
    emoji: '🗺️',
    title: 'The Redistricting Map',
    body: `Your party controls the pen that redraws the district lines. A few careful curves could lock in your majority for a decade — and look exactly as ugly as it is.`,
    choices: [
      {
        label: 'Draw the map to win',
        fx: { influence: 10, base: 6, heat: 8 },
        set: { corrupt_streak: true },
        scandal: { id: 'gerrymander', label: 'the district map you bent', severity: 2 },
        tone: 'slick',
        result: 'The lines slither to your advantage. Safe seats, soft scandal, and a cartographer who will testify someday.',
      },
      {
        label: 'Back an independent commission',
        fx: { support: 10, base: -4, influence: -2 },
        set: { clean_streak: true },
        tone: 'good',
        result: 'You give away the pen to look fair, and look fair you do. Your safe seats get a little less safe.',
      },
    ],
  },
  {
    id: 'p5_b_healthcare',
    paths: ['ballot'],
    phases: [2, 3],
    weight: 8,
    art: 'bulletin',
    emoji: '🏥',
    title: 'The Healthcare Vote',
    body: `Your big reform is finally on the floor. Pass it and you change millions of lives; water it down and you can actually get the votes. Purity or arithmetic.`,
    choices: [
      {
        label: 'Hold out for the full, bold version',
        roll: {
          stat: 'support',
          dc: 54,
          success: {
            fx: { support: 14, base: 8 },
            text: 'Against the odds, you whip the votes for the real thing. A genuine, generational achievement.',
          },
          fail: {
            fx: { support: -8, base: -4, heat: 4 },
            text: 'You reach for everything and the coalition cracks. The bill dies and the blame lands on you.',
          },
        },
        tone: 'bold',
      },
      {
        label: 'Take the half-loaf compromise',
        fx: { support: 8, influence: 6, base: -2 },
        set: { dealmaker: true },
        tone: 'good',
        result: 'You pass the watered version and call it a start. Real help reaches real people; idealists call it betrayal.',
      },
    ],
  },
  {
    id: 'p5_b_endorsement_war',
    paths: ['ballot'],
    phases: [1, 2],
    weight: 7,
    art: 'scene',
    emoji: '⭐',
    title: 'The Kingmaker',
    body: `A revered elder statesman, whose blessing moves voters, will endorse you — but only if you adopt their cherished, slightly outdated pet cause.`,
    choices: [
      {
        label: 'Take the blessing, carry the cause',
        fx: { support: 10, influence: 6, base: -2 },
        set: { owes_elder: true },
        tone: 'slick',
        result: 'The elder anoints you on a sunny stage. You also inherit a position you would not have chosen.',
      },
      {
        label: 'Win without them',
        fx: { base: 8, support: -2, media: 2 },
        tone: 'bold',
        result: 'You decline the strings and the blessing both. Independence looks good until you need that last point.',
      },
    ],
  },
  {
    id: 'p5_b_volunteer',
    paths: ['ballot'],
    phases: [1, 2],
    weight: 6,
    art: 'scene',
    emoji: '📱',
    title: 'The Volunteer’s Mistake',
    body: `An overeager young volunteer posted something ugly under the campaign banner. It is climbing fast, and it is technically your name on the account.`,
    choices: [
      {
        label: 'Take responsibility, handle it with grace',
        fx: { support: 6, media: 4, base: -2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You own the lapse, apologize cleanly, and protect the kid. Accountability, gracefully done, disarms the pile-on.',
      },
      {
        label: 'Throw the volunteer to the wolves',
        fx: { media: 4, heat: 4, base: -4 },
        tone: 'slick',
        result: 'You fire them loudly and move on. The story dies; your own staff quietly notes how fast you cut a rope.',
      },
    ],
  },
  {
    id: 'p5_b_polling_dip',
    paths: ['ballot'],
    phases: [2, 3],
    weight: 7,
    art: 'newspaper',
    emoji: '📉',
    title: 'The Sudden Slump',
    body: `Your numbers have fallen off a cliff for reasons no one can quite name. The panicked consultants want a dramatic reinvention; your gut says hold the course.`,
    choices: [
      {
        label: 'Reinvent — new look, new message',
        roll: {
          stat: 'media',
          dc: 52,
          success: {
            fx: { media: 8, support: 10 },
            text: 'The reboot lands and the narrative flips to "comeback." Reinvention, when it works, looks like genius.',
          },
          fail: {
            fx: { support: -8, base: -4 },
            text: 'The makeover reeks of desperation. "Who are they even anymore?" becomes the question.',
          },
        },
        tone: 'slick',
      },
      {
        label: 'Hold your nerve and your message',
        fx: { base: 8, support: 4 },
        tone: 'bold',
        result: 'You refuse to panic and ride it out. Sometimes a slump is just weather; you decline to call it climate.',
      },
    ],
  },
  {
    id: 'p5_b_townhall_walkout',
    paths: ['ballot'],
    phases: [1, 2, 3],
    weight: 6,
    art: 'scene',
    emoji: '🚶',
    title: 'The Staged Walkout',
    body: `A bloc of activists rises mid-speech and walks out in choreographed protest, cameras conveniently positioned. The room — and the clip — is now yours to shape.`,
    choices: [
      {
        label: 'Invite them to stay and be heard',
        fx: { support: 8, media: 6, base: -2 },
        set: { peacemaker: true },
        tone: 'good',
        result: 'You call after them to come back and talk. The graciousness upstages the stunt entirely.',
      },
      {
        label: 'Mock them as they go',
        fx: { base: 8, media: 2, support: -4, heat: 2 },
        tone: 'bold',
        result: 'You get off a sharp line at their backs. Your crowd laughs; the clip cuts both ways forever.',
      },
    ],
  },
  {
    id: 'p5_b_corruption_probe',
    paths: ['ballot'],
    phases: [2, 3],
    weight: 7,
    art: 'newspaper',
    emoji: '🔎',
    title: 'The Ethics Probe',
    body: `An ethics committee opens an inquiry into your office’s spending. There is probably nothing damning in there. Probably. The word "probably" is doing a lot of work.`,
    choices: [
      {
        label: 'Cooperate fully and transparently',
        fx: { support: 6, base: 4, heat: -4 },
        set: { clean_streak: true },
        tone: 'good',
        result: 'You open the books and the calendars. Transparency is dull, which is exactly what you want it to be.',
      },
      {
        label: 'Stonewall behind procedure',
        fx: { influence: 4, heat: 10, support: -4 },
        scandal: { id: 'ethics_stonewall', label: 'the inquiry you stonewalled', severity: 2 },
        tone: 'slick',
        result: 'Your lawyers turn the probe into a maze. It works, and the maze itself becomes the story.',
      },
    ],
  },

  // ---------------- VANGUARD ----------------
  {
    id: 'p5_v_purge_quota',
    paths: ['vanguard'],
    phases: [2, 3],
    weight: 8,
    art: 'bulletin',
    emoji: '📋',
    title: 'The Quota of Names',
    body: `The organs have sent down a number: this many enemies are to be found in your district by month’s end. The enemies do not exist, but the quota does.`,
    choices: [
      {
        label: 'Fill the quota with real names',
        fx: { base: 10, influence: 6, support: -8, heat: 6 },
        inc: { purge_count: 2 },
        set: { bloody_hands: true, tyrant_rep: true },
        tone: 'bold',
        result: 'You hand up a list of the inconvenient and the unlucky. The quota is met. So is a line you cannot uncross.',
      },
      {
        label: 'Pad it with the already-dead and fled',
        roll: {
          stat: 'influence',
          dc: 54,
          success: {
            fx: { influence: 6, support: 8, heat: -2 },
            text: 'You fill the list with the deceased and the long-gone. The number satisfies the Centre and harms no living soul.',
          },
          fail: {
            fx: { heat: 14, support: -4 },
            text: 'An auditor notices your "enemies" are suspiciously hard to arrest. Questions follow you home.',
          },
        },
        set: { secret_reformer: true },
        tone: 'slick',
      },
    ],
  },
  {
    id: 'p5_v_samizdat',
    paths: ['vanguard'],
    phases: [1, 2],
    weight: 7,
    art: 'scene',
    emoji: '🗞️',
    title: 'The Samizdat',
    body: `A carbon-copied underground pamphlet is passing hand to hand — funny, true, and treasonous. You could trace it, crush it, or simply fail, very hard, to find it.`,
    choices: [
      {
        label: 'Hunt the press, make arrests',
        fx: { base: 8, influence: 4, support: -6 },
        inc: { purge_count: 1 },
        set: { zealot_rep: true },
        tone: 'bold',
        result: 'You find the typewriter and the hands that fed it. The pamphlets stop; the legend of them grows.',
      },
      {
        label: 'Read it, smile, and look elsewhere',
        fx: { support: 6, heat: 6 },
        set: { secret_reformer: true },
        tone: 'good',
        result: 'You pocket a copy and direct the search at empty rooms. Truth survives another week on your watch.',
      },
    ],
  },
  {
    id: 'p5_v_monument',
    paths: ['vanguard'],
    phases: [2, 3],
    weight: 7,
    art: 'bulletin',
    emoji: '🗿',
    title: 'The Predecessor’s Statue',
    body: `The old leader is out of favor, and the question of their enormous statue in the square is now, delicately, yours. Topple it loudly or relocate it quietly?`,
    choices: [
      {
        label: 'Tear it down with great fanfare',
        fx: { base: 8, media: 6, heat: 6 },
        set: { climber_rep: true },
        tone: 'bold',
        result: 'You stage the toppling for the cameras. The crowd cheers the new era and learns how fast eras end.',
      },
      {
        label: 'Quietly move it to a field somewhere',
        fx: { influence: 6, support: 2, heat: -2 },
        tone: 'slick',
        result: 'You have it gone by dawn with no ceremony. No spectacle, no backlash, no martyr in bronze.',
      },
    ],
  },
  {
    id: 'p5_v_defector_family',
    paths: ['vanguard'],
    phases: [2, 3],
    weight: 7,
    art: 'scene',
    emoji: '👪',
    title: 'The Defector’s Family',
    body: `A prominent figure has defected abroad, humiliating the Centre. Their elderly parents and young children remain, and the question of what happens to them lands on you.`,
    choices: [
      {
        label: 'Quietly protect the innocent family',
        fx: { support: 10, base: -4, heat: 8 },
        set: { secret_reformer: true, honest_rep: true },
        tone: 'good',
        result: 'You bury the paperwork that would punish children for a parent’s choice. A risk, taken quietly, for decency.',
      },
      {
        label: 'Make an example of them',
        fx: { base: 8, influence: 4, support: -8 },
        inc: { purge_count: 1 },
        set: { bloody_hands: true },
        tone: 'bold',
        result: 'You let the family pay the defector’s bill. The message is received; so is the kind of person you have become.',
      },
    ],
  },
  {
    id: 'p5_v_war_hero',
    paths: ['vanguard'],
    phases: [2, 3],
    weight: 7,
    art: 'rival',
    emoji: '🎖️',
    title: 'The Inconvenient Hero',
    speaker: (S) => ({ name: S.opp, role: 'a decorated rival', avatar: S.oppAvatar }),
    body: (S) =>
      `${S.opp}, a decorated war hero, is dangerously beloved — the kind of popularity that makes the Centre nervous and makes you a useful knife.`,
    choices: [
      {
        label: 'Engineer their downfall',
        roll: {
          stat: 'influence',
          dc: 54,
          success: {
            fx: { influence: 10, base: 6, heat: 6 },
            text: 'You assemble a quiet case and the hero is reassigned to obscurity. The Centre is grateful; you are feared.',
          },
          fail: {
            fx: { heat: 12, support: -6 },
            text: 'Your move against a beloved figure is clumsy and seen. Sympathy hardens around them, suspicion around you.',
          },
        },
        npcFx: { id: 'antagonist', relationship: -16 },
        inc: { purge_count: 1 },
        tone: 'bold',
      },
      {
        label: 'Befriend them instead',
        fx: { influence: 6, support: 6, base: 2 },
        npcFx: { id: 'antagonist', relationship: 14 },
        set: { has_network: true },
        tone: 'slick',
        result: 'You tie yourself to the hero’s star rather than snuffing it. A powerful friend, and a powerful liability.',
      },
    ],
  },
  {
    id: 'p5_v_committee',
    paths: ['vanguard'],
    phases: [3],
    weight: 9,
    art: 'bulletin',
    emoji: '🪑',
    title: 'The Central Committee Vote',
    body: `A vote that will reshape the top of the Party is coming, and the blocs are forming. Your handful of proxies could tip it — to a reformer, a hardliner, or to chaos you can exploit.`,
    choices: [
      {
        label: 'Throw your weight behind the reformer',
        fx: { support: 10, influence: 6, base: -6, heat: 6 },
        set: { secret_reformer: true, peacemaker: true },
        tone: 'good',
        result: 'You spend your proxies on the gentler future. If they win, you rise with them; if not, your vote is on record.',
      },
      {
        label: 'Back the hardliner and bank the favor',
        fx: { base: 10, influence: 8, support: -4 },
        set: { has_network: true },
        tone: 'slick',
        result: 'You back the iron fist and the debt it owes you. Safe, cynical, and very much survivable.',
      },
    ],
  },
  {
    id: 'p5_v_disaster_cover',
    paths: ['vanguard'],
    phases: [1, 2],
    weight: 7,
    art: 'crisis',
    emoji: '🏭',
    title: 'The Industrial Accident',
    body: `A rushed factory under your authority has failed catastrophically, with a grim toll. The Centre must never learn it was haste, not sabotage, that did it.`,
    choices: [
      {
        label: 'Bury it; blame a wrecker',
        fx: { influence: 6, base: 4, heat: 12, support: -6 },
        inc: { purge_count: 1 },
        set: { bloody_hands: true },
        scandal: { id: 'factory_coverup', label: 'the accident you blamed on a scapegoat', severity: 3 },
        tone: 'slick',
        result: 'You pin it on an innocent "saboteur" and move on. The truth is buried with the victims, for now.',
      },
      {
        label: 'Report it honestly and take the hit',
        fx: { support: 8, influence: -8, base: -2 },
        set: { honest_rep: true },
        tone: 'bold',
        result: 'You tell the Centre it was haste and accept the consequences. Honesty here is nearly a form of suicide; you choose it anyway.',
      },
    ],
  },

  // ---------------- SHARED ----------------
  {
    id: 'p5_s_documentary',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 6,
    art: 'scene',
    emoji: '🎬',
    title: 'The Documentary Crew',
    body: `A respected filmmaker wants months of fly-on-the-wall access. Handled well it is a flattering legacy; handled badly it is a hundred hours of evidence.`,
    choices: [
      {
        label: 'Grant deep, unguarded access',
        roll: {
          stat: 'media',
          dc: 52,
          success: {
            fx: { media: 12, support: 8 },
            text: 'The candor reads as confidence and the film canonizes you. A gamble that paid in legend.',
          },
          fail: {
            fx: { media: -6, heat: 8 },
            text: 'The camera catches a temper, a contradiction, a cruelty. The edit is not on your side.',
          },
        },
        tone: 'bold',
      },
      {
        label: 'Give them a tightly managed version',
        fx: { media: 6, base: 2 },
        tone: 'slick',
        result: 'You allow only the choreographed moments. The film is glossy, safe, and faintly unconvincing.',
      },
    ],
  },
  {
    id: 'p5_s_health_scare',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 6,
    art: 'scene',
    emoji: '🩻',
    title: 'The Health Scare',
    body: `A routine check turns up something that needs watching. Nothing urgent, the doctors say — but in your position, a private fact is always one leak from a public crisis.`,
    choices: [
      {
        label: 'Disclose it plainly and carry on',
        fx: { support: 8, media: 4, base: 2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You tell the public the truth and keep working. Candor about being mortal, oddly, makes you more trusted.',
      },
      {
        label: 'Keep it absolutely secret',
        fx: { influence: 4, heat: 6, support: -2 },
        set: { stonewaller: true },
        tone: 'slick',
        result: 'You bury the file and project vigor. The secret holds — a small, ticking thing in a locked drawer.',
      },
    ],
  },
  {
    id: 'p5_s_ghostwriter',
    paths: ['ballot', 'vanguard'],
    phases: [1, 2, 3],
    weight: 6,
    art: 'newspaper',
    emoji: '✍️',
    title: 'The Vision Book',
    body: `Your "memoir of ideas" is due, and a talented ghostwriter has drafted it. It is better than anything you would write — and it puts bold words in your mouth you may have to defend.`,
    choices: [
      {
        label: 'Publish the bold version under your name',
        fx: { media: 8, base: 6, heat: 4 },
        tone: 'bold',
        result: 'The book is a sensation and the ideas are now yours to own, live, on every stage, forever.',
      },
      {
        label: 'Sand down the riskier passages',
        fx: { media: 4, support: 2 },
        tone: 'slick',
        result: 'You blunt the sharp edges into safe platitudes. It sells modestly and commits you to nothing.',
      },
    ],
  },
  {
    id: 'p5_s_satire',
    paths: ['ballot', 'vanguard'],
    phases: [1, 2, 3],
    weight: 6,
    art: 'scene',
    emoji: '🎭',
    title: 'The Mocking Mural',
    body: `A wickedly funny caricature of you has appeared — on a wall, on every phone, on the lips of comedians. How you react becomes the next, larger joke.`,
    choices: [
      {
        label: 'Laugh along and buy the original',
        fx: { support: 8, media: 6, base: -2 },
        tone: 'good',
        result: 'You praise the artist’s nerve and hang a copy in your office. Good humor turns the mockery into your applause.',
      },
      {
        label: 'Try to have it taken down',
        fx: { heat: 8, base: 2, support: -6 },
        tone: 'bold',
        result: 'You send someone to scrub the wall. By nightfall the image is on ten thousand walls and your humorlessness is the headline.',
      },
    ],
  },
  {
    id: 'p5_s_anniversary',
    paths: ['ballot', 'vanguard'],
    phases: [3],
    weight: 6,
    art: 'bulletin',
    emoji: '🎗️',
    title: 'The Anniversary',
    body: `It is a decade since you first took office, and the occasion demands a speech. You can dwell on the gleaming legacy, or admit, just once, what you would do differently.`,
    choices: [
      {
        label: 'Trumpet the unblemished legacy',
        fx: { media: 8, base: 6, heat: 2 },
        set: { cult_building: true },
        tone: 'bold',
        result: 'You recite triumphs and omit the rest. The faithful roar; the historians sharpen their pens.',
      },
      {
        label: 'Admit a real regret',
        fx: { support: 10, base: -2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You name one true mistake out loud. Vulnerability, from a decade in power, lands like a thunderclap of honesty.',
      },
    ],
  },

  // ---------------- CRISES ----------------
  {
    id: 'p5_c_refugees',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 9,
    crisis: true,
    art: 'crisis',
    emoji: '⛺',
    title: 'The Refugee Wave',
    body: `War next door has sent a tide of frightened families to your border. Open arms strain the country; closed gates strain the conscience and the cameras.`,
    choices: [
      {
        label: 'Open the border and organize relief',
        roll: {
          stat: 'support',
          dc: 52,
          success: {
            fx: { support: 12, media: 6, funds: -8 },
            text: 'You welcome them with order and dignity. The cost is real; so is the moral standing it buys.',
          },
          fail: {
            fx: { support: -8, heat: 8 },
            text: 'Goodwill outruns logistics; the camps overflow and the backlash builds. Mercy, badly resourced, becomes a crisis.',
          },
        },
        set: { peacemaker: true },
        tone: 'good',
      },
      {
        label: 'Seal the border, project control',
        fx: { base: 10, heat: 8, support: -6 },
        tone: 'bold',
        result: 'You close the gates and the hardliners cheer. The images at the fence are not ones you will want remembered.',
      },
    ],
  },
  {
    id: 'p5_c_terror',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 9,
    crisis: true,
    art: 'crisis',
    emoji: '🚨',
    title: 'The Attack',
    body: `A bomb in a crowded square. The wounded are still being counted, the public is terrified and furious, and every word you say in the next hour will echo for years.`,
    choices: [
      {
        label: 'Steady the nation; resist overreach',
        roll: {
          stat: 'support',
          dc: 52,
          success: {
            fx: { support: 14, base: 8, influence: 4 },
            text: 'You grieve with the country and refuse to let fear rewrite its laws. Restraint, in that moment, is leadership.',
          },
          fail: {
            fx: { support: -6, heat: 6 },
            text: 'Your calm is mistaken for weakness by a frightened public baying for action. The polls punish patience.',
          },
        },
        tone: 'good',
      },
      {
        label: 'Seize emergency powers',
        fx: { base: 10, influence: 8, heat: 12, support: -4 },
        inc: { purge_count: 1 },
        set: { bloody_hands: true, tyrant_rep: true },
        tone: 'bold',
        result: 'You take sweeping new powers "for the duration." Emergencies, history notes, have a way of never quite ending.',
      },
    ],
  },
  {
    id: 'p5_c_bank_run',
    paths: ['ballot', 'vanguard'],
    phases: [1, 2, 3],
    weight: 9,
    crisis: true,
    art: 'crisis',
    emoji: '🏦',
    title: 'The Bank Run',
    body: `A rumor has become a stampede: lines snake around every bank, and the whole financial system could seize by closing time. Confidence is the only thing holding it up, and it is evaporating.`,
    choices: [
      {
        label: 'Guarantee every deposit, publicly',
        roll: {
          stat: 'influence',
          dc: 50,
          success: {
            fx: { influence: 10, support: 10, funds: -8 },
            text: 'You put the full faith of the state behind the savings, and the panic exhales. A bluff that had to work, and did.',
          },
          fail: {
            fx: { support: -8, heat: 8 },
            text: 'The guarantee is doubted and the lines grow. Promising everything, and being disbelieved, is the worst outcome.',
          },
        },
        tone: 'bold',
      },
      {
        label: 'Order a bank holiday to stop the bleed',
        fx: { influence: 6, support: -4, heat: 6 },
        tone: 'slick',
        result: 'You freeze the system to break the panic. It works, roughly, and everyone remembers the day their money was locked away.',
      },
    ],
  },
  {
    id: 'p5_c_wildfire',
    paths: ['ballot', 'vanguard'],
    phases: [1, 2, 3],
    weight: 8,
    crisis: true,
    art: 'crisis',
    emoji: '🔥',
    title: 'The Fire Season',
    body: `Walls of flame are eating the dry hills and marching on the towns. The crews are stretched to breaking, and the smoke has reached the capital and the front pages.`,
    choices: [
      {
        label: 'Pour every resource into the fight',
        fx: { support: 10, funds: -12, base: 4 },
        tone: 'good',
        result: 'You throw the treasury at the flames and stand with the crews. Expensive, exhausting, and the right call.',
      },
      {
        label: 'Manage the optics, ration the response',
        roll: {
          stat: 'media',
          dc: 50,
          success: {
            fx: { media: 6, funds: -4 },
            text: 'You stage the right photos and spend the minimum. The coverage is kind; the hills, less so.',
          },
          fail: {
            fx: { support: -10, heat: 8 },
            text: 'A town you under-resourced burns on live television. The optics you managed manage you instead.',
          },
        },
        tone: 'slick',
      },
    ],
  },
  {
    id: 'p5_c_chemical',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 8,
    crisis: true,
    art: 'crisis',
    emoji: '☣️',
    title: 'The Chemical Spill',
    body: `A derailed tanker has poisoned a river that feeds three towns. The company is stalling, the water is suspect, and the people want to know if it is safe to give their children a drink.`,
    choices: [
      {
        label: 'Order a hard shutdown and full disclosure',
        fx: { support: 12, funds: -8, heat: -2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You cut the water, truck in clean supplies, and tell the truth fast. Costly, correct, and trusted.',
      },
      {
        label: 'Reassure the public while you study it',
        roll: {
          stat: 'media',
          dc: 52,
          success: {
            fx: { media: 6, base: 4 },
            text: 'Your calm holds and the tests come back survivable. You bought time and, this once, it paid off.',
          },
          fail: {
            fx: { support: -12, heat: 12 },
            text: 'The "it’s fine" briefing ages horribly when the test results leak. Reassurance becomes cover-up in one news cycle.',
          },
        },
        scandal: { id: 'water_spin', label: 'the water you called safe', severity: 2 },
        tone: 'slick',
      },
    ],
  },
];
