import type { GameEvent } from '../engine/types';

/**
 * Content pack 3 — third volume expansion toward a commercial-size bank, tilted
 * toward early-game depth (the thinnest cells were phase 1, especially on the
 * vanguard path) plus phase-3 capstone dilemmas and two new crises. Choices set
 * flags the ending logic actually reads (secret_reformer, bloody_hands,
 * corrupt_streak, cult_building, has_network, purge_count) so they carry
 * downstream weight. Two delayed then-chains (the machine's favor; the reform
 * circle exposed). Fictional and non-partisan by construction.
 */
export const PACK_3: GameEvent[] = [
  // ---------------- BALLOT ----------------
  {
    id: 'p3_b_first_rally',
    paths: ['ballot'],
    phases: [1, 2],
    weight: 9,
    art: 'scene',
    emoji: '📢',
    title: 'Your First Big Rally',
    body: `The hall is half-empty an hour before doors, and your stomach knows it. Then people trickle in, then pour in. The microphone waits.`,
    choices: [
      {
        label: 'Swing for a barn-burner of a speech',
        roll: {
          stat: 'media',
          dc: 48,
          success: {
            fx: { media: 10, support: 8, base: 6 },
            text: 'You find a rhythm and the room finds its feet. The clip of the crowd roaring does your fundraising for a week.',
          },
          fail: {
            fx: { support: -4, base: -2 },
            text: 'You over-reach, lose the thread, and the applause is the polite kind. You will rewrite this speech forever.',
          },
        },
        tone: 'bold',
      },
      {
        label: 'Keep it warm, simple, and human',
        fx: { support: 6, base: 4 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You skip the fireworks and just talk to them. It is not viral, but the people in the room believe you.',
      },
    ],
  },
  {
    id: 'p3_b_local_machine',
    paths: ['ballot'],
    phases: [1],
    weight: 8,
    art: 'rival',
    emoji: '🎩',
    title: 'The Local Machine',
    body: `A ward boss with rings on every finger offers you turnout no volunteer army can match — a wall of votes, delivered. Nothing is free in his arithmetic.`,
    choices: [
      {
        label: 'Take the machine’s turnout',
        fx: { support: 12, base: 6, heat: 8 },
        set: { owes_boss: true, corrupt_streak: true },
        then: [{ id: 'p3_b_machine_due', inTurns: 3 }],
        tone: 'slick',
        result: 'The numbers arrive like clockwork. So, eventually, will the boss, with a list of what he expects.',
      },
      {
        label: 'Build your own ground game',
        fx: { base: 10, support: 2, funds: -4 },
        set: { clean_streak: true },
        tone: 'good',
        result: 'You do it the slow way — clipboards, church basements, sore feet. It is yours, and no one can repossess it.',
      },
    ],
  },
  {
    id: 'p3_b_machine_due',
    paths: ['ballot'],
    phases: [1, 2, 3],
    weight: 6,
    queueOnly: true,
    art: 'rival',
    emoji: '🧾',
    title: 'The Boss Collects',
    body: `The ward boss who handed you a wall of votes is in your doorway now, smiling, with a contract he would very much like you to bless.`,
    choices: [
      {
        label: 'Sign the sweetheart deal',
        fx: { funds: 6, base: 4, heat: 12 },
        set: { corrupt_streak: true },
        scandal: { id: 'machine_contract', label: 'the boss’s no-bid contract', severity: 2 },
        tone: 'slick',
        result: 'You bless the contract. The boss is satisfied, and you are now a name in his ledger forever.',
      },
      {
        label: 'Refuse and burn the bridge',
        fx: { base: -8, support: 6, heat: -4 },
        set: { defied_boss: true },
        tone: 'bold',
        result: 'You tell him no. He takes his machine and his grudge home. Both will be back.',
      },
    ],
  },
  {
    id: 'p3_b_door_knock',
    paths: ['ballot'],
    phases: [1, 2],
    weight: 7,
    art: 'scene',
    emoji: '🚪',
    title: 'The Grind',
    body: `It is cold, it is raining, and there are four hundred more doors. Your staff suggests you could just do a fundraiser call-time block instead.`,
    choices: [
      {
        label: 'Knock every door yourself',
        fx: { base: 10, support: 6, funds: -2 },
        set: { grassroots: true, clean_streak: true },
        tone: 'good',
        result: 'You shake cold hands until yours go numb. The local paper runs a photo titled, simply, "Showed Up."',
      },
      {
        label: 'Spend the day dialing donors',
        fx: { funds: 12, base: -4 },
        tone: 'slick',
        result: 'You raise a tidy sum from a warm chair. The doors go unknocked, and someone notices which you chose.',
      },
    ],
  },
  {
    id: 'p3_b_convention',
    paths: ['ballot'],
    phases: [3],
    weight: 12,
    art: 'newspaper',
    emoji: '🎉',
    title: 'The Convention Speech',
    body: `Tens of thousands in the hall, tens of millions at home, and a teleprompter holding the most important words of your life. This is the moment that becomes the montage.`,
    choices: [
      {
        label: 'Reach for history — go big',
        roll: {
          stat: 'media',
          dc: 55,
          success: {
            fx: { media: 14, support: 12, base: 6 },
            text: 'You deliver the speech of a generation. Grown strategists weep. The bounce is enormous.',
          },
          fail: {
            fx: { media: -6, support: -6, heat: 4 },
            text: 'You aim for the rafters and clip a wing. The pundits call it "ambitious," which is not a compliment.',
          },
        },
        tone: 'bold',
      },
      {
        label: 'Give the safe, unifying address',
        fx: { support: 8, media: 6, base: 2 },
        tone: 'good',
        result: 'You hit every mark and offend no one. Solid, presidential, forgettable — exactly as designed.',
      },
    ],
  },
  {
    id: 'p3_b_october_surprise',
    paths: ['ballot'],
    phases: [2, 3],
    weight: 8,
    art: 'rival',
    emoji: '🃏',
    title: 'The October Surprise',
    speaker: (S) => ({ name: S.opp, role: 'your rival', avatar: S.oppAvatar }),
    body: (S) =>
      `Days before the vote, ${S.opp}’s camp drops a damaging story about you — timed for maximum damage and minimum time to respond. The clock is a weapon now.`,
    choices: [
      {
        label: 'Hit back hard and immediately',
        roll: {
          stat: 'media',
          dc: 53,
          success: {
            fx: { media: 8, support: 8, heat: 4 },
            text: 'You flood the zone with your own narrative before theirs sets. The surprise fizzles on the launch pad.',
          },
          fail: {
            fx: { support: -10, heat: 8 },
            text: 'Your scramble looks like panic, which looks like guilt. The story grows legs and runs.',
          },
        },
        npcFx: { id: 'antagonist', relationship: -12 },
        tone: 'bold',
      },
      {
        label: 'Stay calm and let allies carry the rebuttal',
        fx: { support: 2, base: 2, media: -2 },
        tone: 'good',
        result: 'You keep your dignity and let surrogates do the brawling. Slower, steadier, and your hands stay clean.',
      },
    ],
  },

  // ---------------- VANGUARD ----------------
  {
    id: 'p3_v_first_posting',
    paths: ['vanguard'],
    phases: [1],
    weight: 9,
    art: 'bulletin',
    emoji: '🗄️',
    title: 'Your First Posting',
    body: `A grey ministry, a grey desk, and a stack of files that decide other people’s lives. The clerk who shows you around mentions, lightly, who reports on whom.`,
    choices: [
      {
        label: 'Master the paperwork; become indispensable',
        fx: { influence: 10, base: 4 },
        set: { has_network: true },
        tone: 'slick',
        result: 'You learn which form moves which mountain. Quietly, you become the person who knows where everything is.',
      },
      {
        label: 'Quietly protect the people in the files',
        fx: { support: 8, base: 4, heat: 4 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You misfile the right things and lose the dangerous ones. Small mercies, and a small, growing risk.',
      },
    ],
  },
  {
    id: 'p3_v_denunciation',
    paths: ['vanguard'],
    phases: [1, 2],
    weight: 9,
    art: 'bulletin',
    emoji: '📛',
    title: 'The Denunciation',
    body: `A colleague — competent, decent, and now suddenly "unreliable" — is to be denounced at the section meeting. Everyone will be watching whether you raise your hand.`,
    choices: [
      {
        label: 'Denounce them loudly',
        fx: { base: 8, influence: 6, support: -6, heat: 4 },
        inc: { purge_count: 1 },
        set: { bloody_hands: true },
        tone: 'bold',
        result: 'You read the charges with conviction you do not feel. Your colleague is gone by morning. You are noticed.',
      },
      {
        label: 'Stay silent and study your shoes',
        fx: { heat: 6, base: -2 },
        tone: 'slick',
        result: 'You neither accuse nor defend. Silence is the cowardice that lets you survive to the next meeting.',
      },
      {
        label: 'Quietly warn them the night before',
        req: (S) => S.stats.influence >= 12,
        reqText: 'Needs Standing 12+',
        fx: { support: 8, influence: -6, heat: 6 },
        set: { secret_reformer: true },
        tone: 'good',
        result: 'A whispered word in a stairwell. They vanish before the meeting — fled, not arrested. A debt is owed, and a risk is taken.',
      },
    ],
  },
  {
    id: 'p3_v_study_circle',
    paths: ['vanguard'],
    phases: [1, 2],
    weight: 8,
    art: 'scene',
    emoji: '📚',
    title: 'The Study Circle',
    body: `In a back room that smells of cigarettes and daring, a few trusted people read the banned books and imagine a gentler country. They want to know if you are one of them.`,
    choices: [
      {
        label: 'Join them — quietly believe',
        fx: { support: 8, base: 4, heat: 8 },
        set: { secret_reformer: true },
        then: [{ id: 'p3_v_circle_exposed', inTurns: 4 }],
        tone: 'good',
        result: 'You take a seat and a great risk. For the first time in years, hope feels less like a liability.',
      },
      {
        label: 'Decline — too dangerous to dream',
        fx: { influence: 4, base: 2, heat: -4 },
        tone: 'slick',
        result: 'You make your excuses and leave the books unread. Some windows are safer left painted shut.',
      },
      {
        label: 'Report the circle to the organs',
        fx: { base: 10, influence: 6, support: -8 },
        inc: { purge_count: 1 },
        set: { bloody_hands: true, zealot_rep: true },
        tone: 'bold',
        result: 'You give the names. The back room is emptied that week, and your file gains a gold star and a stain.',
      },
    ],
  },
  {
    id: 'p3_v_circle_exposed',
    paths: ['vanguard'],
    phases: [1, 2, 3],
    weight: 6,
    queueOnly: true,
    art: 'crisis',
    emoji: '🔦',
    title: 'The Circle Is Exposed',
    body: `The study circle has been discovered, and an investigator with patient eyes is asking everyone, one by one, who else attended. Your name is a question away.`,
    choices: [
      {
        label: 'Deny everything, coldly',
        roll: {
          stat: 'influence',
          dc: 55,
          success: {
            fx: { influence: 6, base: 4, heat: -4 },
            text: 'You meet the patient eyes with colder ones and give nothing. The thread leads away from you.',
          },
          fail: {
            fx: { heat: 16, support: -8 },
            text: 'Your denial is a beat too fast. The investigator writes something down and underlines it.',
          },
        },
        tone: 'slick',
      },
      {
        label: 'Take the fall to shield the others',
        fx: { support: 12, influence: -10, heat: 10 },
        set: { secret_reformer: true, martyr_rep: true },
        tone: 'bold',
        result: 'You absorb the blame so the rest go free. It costs you dearly, and somewhere a handful of people will never forget it.',
      },
    ],
  },
  {
    id: 'p3_v_zeal_audition',
    paths: ['vanguard'],
    phases: [1],
    weight: 8,
    art: 'bulletin',
    emoji: '🔥',
    title: 'Auditioning Your Zeal',
    body: `At the rally, the truest believers compete to chant the loudest and pledge the most. Fervor is being measured, and your volume is your résumé.`,
    choices: [
      {
        label: 'Out-zealot the zealots',
        fx: { base: 12, media: 4, support: -4, heat: 4 },
        set: { hardliner_cred: true },
        tone: 'bold',
        result: 'You bellow the slogans loudest of all. The doctrinaire wing claims you as theirs, for better and worse.',
      },
      {
        label: 'Clap along, mean none of it',
        fx: { heat: 4, influence: 2 },
        tone: 'slick',
        result: 'You move your lips and save your voice. Performed fervor is cheaper than the real thing and just as visible.',
      },
    ],
  },
  {
    id: 'p3_v_succession',
    paths: ['vanguard'],
    phases: [3],
    weight: 10,
    art: 'rival',
    emoji: '👑',
    title: 'The Succession Whisper',
    speaker: (S) => ({ name: S.opp, role: 'a rival heir', avatar: S.oppAvatar }),
    body: (S) =>
      `The old leader is failing, and the corridors hum with the only question that matters: who is next. ${S.opp} is maneuvering openly. The throne is close enough to touch.`,
    choices: [
      {
        label: 'Position yourself as the inevitable heir',
        fx: { influence: 12, base: 8, heat: 10 },
        set: { climber_rep: true },
        npcFx: { id: 'antagonist', relationship: -14 },
        tone: 'bold',
        result: 'You let it be known, without saying it, that the future is you. Your rival sharpens accordingly.',
      },
      {
        label: 'Build a coalition behind a compromise figure',
        fx: { influence: 8, support: 6, base: -2 },
        set: { has_network: true },
        tone: 'slick',
        result: 'You play kingmaker instead of king. Power that is owed to you is sometimes safer than power that is yours.',
      },
    ],
  },
  {
    id: 'p3_v_cult_building',
    paths: ['vanguard'],
    phases: [2, 3],
    weight: 8,
    art: 'bulletin',
    emoji: '🖼️',
    title: 'The Portrait Committee',
    body: `An eager bureau proposes your face on the schoolroom walls, the morning broadcasts, the children’s primers. The machinery of adoration is asking for the green light.`,
    choices: [
      {
        label: 'Let the cult bloom',
        fx: { base: 10, media: 8, support: 4, heat: 6 },
        set: { cult_building: true, own_cult: true },
        tone: 'bold',
        result: 'Your portrait multiplies overnight. To be everywhere at once is a kind of immortality and a kind of prison.',
      },
      {
        label: 'Forbid it — "the Party, not the man"',
        fx: { support: 8, base: -2, heat: -4 },
        set: { ascetic_rep: true },
        tone: 'good',
        result: 'You order your own face taken down. Modesty, performed at scale, is its own quiet kind of power.',
      },
    ],
  },

  // ---------------- SHARED ----------------
  {
    id: 'p3_s_family_ask',
    paths: ['ballot', 'vanguard'],
    phases: [1, 2],
    weight: 7,
    art: 'scene',
    emoji: '👨‍👩‍👦',
    title: 'Blood and Office',
    body: `A relative wants a posting they have not earned. Family loyalty pulls one way; the appearance of nepotism, and your own thin patience, pull the other.`,
    choices: [
      {
        label: 'Find them a comfortable sinecure',
        fx: { base: 4, heat: 8, support: -4 },
        set: { nepotism: true, corrupt_streak: true },
        scandal: { id: 'family_sinecure', label: 'the relative on the payroll', severity: 1 },
        tone: 'slick',
        result: 'You make the call. Blood is honored, and a future headline is quietly written and filed.',
      },
      {
        label: 'Tell them no, gently but firmly',
        fx: { base: -2, support: 6, influence: 2 },
        set: { clean_streak: true },
        tone: 'good',
        result: 'You hold the line and weather the cold silence at the next family dinner. Principles are expensive at home.',
      },
    ],
  },
  {
    id: 'p3_s_idealism',
    paths: ['ballot', 'vanguard'],
    phases: [1, 2],
    weight: 7,
    art: 'scene',
    emoji: '🕯️',
    title: 'A Late Night of Conviction',
    body: `Past midnight, alone with a draft, you can write the careful speech your handlers approved — or the honest one you actually believe.`,
    choices: [
      {
        label: 'Publish the honest one',
        roll: {
          stat: 'support',
          dc: 50,
          success: {
            fx: { support: 12, base: 8 },
            text: 'You say the true thing plainly, and it lands. People are starved for someone who means it.',
          },
          fail: {
            fx: { support: -6, heat: 6 },
            text: 'You say the true thing and it is promptly clipped, twisted, and weaponized. Honesty is a gamble.',
          },
        },
        set: { peacemaker: true },
        tone: 'bold',
      },
      {
        label: 'Run the safe, approved draft',
        fx: { media: 4, support: 2, base: -2 },
        tone: 'slick',
        result: 'You file the version that survives a focus group. It says little and risks nothing, which is the point.',
      },
    ],
  },
  {
    id: 'p3_s_old_rival_truce',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 7,
    art: 'rival',
    emoji: '🤝',
    title: 'The Offered Truce',
    speaker: (S) => ({ name: S.opp, role: 'your old adversary', avatar: S.oppAvatar }),
    body: (S) =>
      `${S.opp}, who has fought you at every rung, requests a private meeting and — astonishingly — offers a truce. It could be sincere. It could be a trap with good manners.`,
    choices: [
      {
        label: 'Accept the truce in good faith',
        fx: { influence: 8, support: 6, base: -2 },
        npcFx: { id: 'antagonist', relationship: 18 },
        tone: 'good',
        result: 'You shake hands and mean it. The war cools, and you both, briefly, remember you were once just people.',
      },
      {
        label: 'Smile, agree, and prepare a knife',
        fx: { influence: 6, heat: 6, base: 2 },
        npcFx: { id: 'antagonist', relationship: -10 },
        set: { backstabber: true },
        tone: 'slick',
        result: 'You toast the truce and keep one hand behind your back. Trust is a resource you have chosen not to spend.',
      },
    ],
  },
  {
    id: 'p3_s_press_award',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 6,
    art: 'newspaper',
    emoji: '🏅',
    title: 'The Press Dinner',
    body: `The press association hands out its annual awards over bad chicken and worse wine, and tradition demands the powerful roast themselves. The room is full of people who quote you.`,
    choices: [
      {
        label: 'Be self-deprecating and charming',
        fx: { media: 10, support: 4 },
        set: { press_friendly: true },
        tone: 'good',
        result: 'You land the jokes, including the ones at your own expense. The columnists go home a little fonder.',
      },
      {
        label: 'Settle scores from the podium',
        fx: { media: -6, base: 6, heat: 6 },
        tone: 'bold',
        result: 'You use the mic to swing at your critics. Your base loves it; everyone holding a pen remembers it.',
      },
    ],
  },

  // ---------------- CRISES ----------------
  {
    id: 'p3_c_famine',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 10,
    crisis: true,
    art: 'crisis',
    emoji: '🌾',
    title: 'The Harvest Fails',
    body: `A failed harvest meets an empty reserve, and hunger begins to walk the provinces. Pride says project strength; arithmetic says ask for help.`,
    choices: [
      {
        label: 'Swallow your pride and request foreign aid',
        roll: {
          stat: 'support',
          dc: 50,
          success: {
            fx: { support: 12, funds: 6, base: -4 },
            text: 'The grain ships arrive and the queues shorten. Admitting need cost you face and saved a great many lives.',
          },
          fail: {
            fx: { support: -6, heat: 6 },
            text: 'The aid comes with cameras and conditions, and your rivals call it surrender. Full bellies, bruised pride.',
          },
        },
        tone: 'good',
      },
      {
        label: 'Hide the shortage, project abundance',
        fx: { media: 6, influence: 4, support: -8, heat: 10 },
        set: { potemkin: true },
        scandal: { id: 'hidden_famine', label: 'the famine you covered up', severity: 3 },
        tone: 'slick',
        result: 'The newsreels brim with bread while the provinces thin. A secret this size does not stay buried forever.',
      },
    ],
  },
  {
    id: 'p3_c_uprising',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 9,
    crisis: true,
    art: 'crisis',
    emoji: '✊',
    title: 'Unrest in the Streets',
    body: `The squares fill with angry crowds, and the order goes up the chain to you: disperse them, or hear them. The whole nation is watching which you choose.`,
    choices: [
      {
        label: 'Go down and listen to the crowd',
        roll: {
          stat: 'base',
          dc: 52,
          success: {
            fx: { support: 14, base: 8, heat: -4 },
            text: 'You walk into the square unguarded and listen. The gesture stuns everyone, and the anger gives way to something workable.',
          },
          fail: {
            fx: { support: -6, heat: 8 },
            text: 'You try to listen and get shouted down. The optics of a leader drowned out are not kind.',
          },
        },
        set: { peacemaker: true },
        tone: 'good',
      },
      {
        label: 'Order a hard crackdown',
        fx: { base: 6, heat: 16, support: -10 },
        inc: { purge_count: 1 },
        set: { bloody_hands: true, tyrant_rep: true },
        scandal: { id: 'crackdown', label: 'the night you cleared the square', severity: 3 },
        tone: 'bold',
        result: 'The square is empty by dawn and quiet for a reason no one says aloud. The quiet will cost you, later, all at once.',
      },
    ],
  },
  {
    id: 'p3_c_scandal_eve',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 8,
    crisis: true,
    art: 'newspaper',
    emoji: '🗞️',
    title: 'The Story Lands at Midnight',
    body: `A reporter calls for comment on a story running in six hours — one with documents, names, and your fingerprints faintly visible. There is just time to react, badly or well.`,
    choices: [
      {
        label: 'Get ahead of it — confess the small to bury the large',
        roll: {
          stat: 'media',
          dc: 52,
          success: {
            fx: { media: 8, support: 6, heat: -6 },
            text: 'You volunteer a minor sin before they print the major one. The framing becomes yours, and the worst stays unwritten.',
          },
          fail: {
            fx: { support: -10, heat: 10 },
            text: 'Your pre-buttal only confirms there is something to bury. The reporter adds a paragraph and a smile.',
          },
        },
        tone: 'slick',
      },
      {
        label: 'Stonewall and lawyer up',
        fx: { heat: 8, influence: 4, support: -4 },
        set: { stonewaller: true },
        tone: 'bold',
        result: 'You say nothing through expensive intermediaries. The silence holds the line and quietly admits the wound.',
      },
    ],
  },
];
