import type { GameEvent } from '../engine/types';

/**
 * Content pack 7 — seventh volume expansion. Running-mate vetting, tax returns,
 * and union demands (ballot); rewriting the anthem, purging a mentor, the secret
 * archive of crimes (vanguard); doctored footage, whistleblowers, and charity
 * fronts (shared); and five new crises (nuclear plant, an ally assassinated, a
 * winter energy crunch, a mutiny, a rail disaster). Fictional and non-partisan.
 */
export const PACK_7: GameEvent[] = [
  // ---------------- BALLOT ----------------
  {
    id: 'p7_b_vp_vetting',
    paths: ['ballot'],
    phases: [3],
    weight: 7,
    art: 'scene',
    emoji: '🔍',
    title: 'The Vetting',
    body: `Your ideal running mate, who electrifies the base, has a buried problem the vetters just unearthed. You can swallow the risk or drop the dream pick at the worst moment.`,
    choices: [
      {
        label: 'Stick with them and hope it stays buried',
        fx: { base: 8, support: 4, heat: 10 },
        scandal: { id: 'vp_skeleton', label: 'your running mate’s buried problem', severity: 2 },
        tone: 'bold',
        result: 'You keep the exciting pick and the ticking clock that comes with them. The base roars; the vetters sweat.',
      },
      {
        label: 'Cut them loose for a safe choice',
        fx: { influence: 6, support: 2, base: -4 },
        set: { clean_streak: true },
        tone: 'good',
        result: 'You swap fireworks for a sturdy nobody. Dull, defensible, and nobody writes a scandal about beige.',
      },
    ],
  },
  {
    id: 'p7_b_tax_returns',
    paths: ['ballot'],
    phases: [2, 3],
    weight: 6,
    art: 'newspaper',
    emoji: '🧾',
    title: 'The Tax Returns',
    body: `Tradition and rivals demand you publish your tax returns. They are legal — but they reveal a fortune larger, and a charitable streak smaller, than your speeches imply.`,
    choices: [
      {
        label: 'Release them in full',
        fx: { support: 8, media: 4, heat: -4 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You publish everything and take the lumps. A day of awkward headlines buys years without the question.',
      },
      {
        label: 'Stall behind an "ongoing audit"',
        fx: { influence: 4, heat: 8, support: -4 },
        set: { stonewaller: true },
        tone: 'slick',
        result: 'You hide behind paperwork indefinitely. "What are they hiding?" becomes a permanent, low hum.',
      },
    ],
  },
  {
    id: 'p7_b_union',
    paths: ['ballot'],
    phases: [1, 2],
    weight: 7,
    art: 'scene',
    emoji: '🔧',
    title: 'The Union’s Terms',
    body: `A powerful union offers boots on the ground and a wall of votes — if you back a costly demand that business backers will despise. You cannot keep both camps happy.`,
    choices: [
      {
        label: 'Side with the workers',
        fx: { base: 10, support: 6, funds: -6 },
        set: { grassroots: true },
        tone: 'bold',
        result: 'You take the picket line over the boardroom. The volunteers surge; the donor dinners get chilly.',
      },
      {
        label: 'Keep the business money',
        fx: { funds: 12, base: -6, heat: 2 },
        tone: 'slick',
        result: 'You keep the checks and lose the foot soldiers. A richer, lonelier campaign.',
      },
    ],
  },
  {
    id: 'p7_b_caught_lie',
    paths: ['ballot'],
    phases: [1, 2, 3],
    weight: 7,
    art: 'newspaper',
    emoji: '🤥',
    title: 'The Small Lie',
    body: `A minor embellishment in your stump story — a job you didn’t quite hold, a hardship slightly inflated — has been caught and documented. Small, true, and spreading.`,
    choices: [
      {
        label: 'Admit it cleanly and apologize',
        fx: { support: 4, media: 2, heat: -2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You cop to the embellishment fast and plainly. A quick, humble correction starves the story.',
      },
      {
        label: 'Double down and dispute the framing',
        roll: {
          stat: 'media',
          dc: 54,
          success: {
            fx: { base: 6, media: 4 },
            text: 'You brazen it out and muddy the record enough that it fades. Audacity, occasionally, works.',
          },
          fail: {
            fx: { support: -10, heat: 6 },
            text: 'The denial is debunked line by line. Now it is not the lie that sticks, but the cover-up.',
          },
        },
        tone: 'bold',
      },
    ],
  },
  {
    id: 'p7_b_climate',
    paths: ['ballot'],
    phases: [2, 3],
    weight: 7,
    art: 'bulletin',
    emoji: '🏭',
    title: 'Jobs or the River',
    body: `A big employer will build in your district — and quietly poison a beloved river to do it. Hundreds of jobs against the water and woods your voters grew up on.`,
    choices: [
      {
        label: 'Protect the river, refuse the plant',
        fx: { support: 8, base: -4, funds: -4 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You choose the water over the warehouses. The greens cheer; the laid-off do not, and they vote too.',
      },
      {
        label: 'Take the jobs, regulate "later"',
        fx: { funds: 8, base: 8, heat: 6, support: -2 },
        scandal: { id: 'river_deal', label: 'the river you traded for jobs', severity: 1 },
        tone: 'slick',
        result: 'You cut the ribbon on the new plant. The paychecks start; the fish, in a few years, stop.',
      },
    ],
  },
  {
    id: 'p7_b_rally_violence',
    paths: ['ballot'],
    phases: [2, 3],
    weight: 7,
    art: 'crisis',
    emoji: '🪧',
    title: 'The Rally Turns',
    body: `A scuffle at your rally has become a brawl, then a viral clip of your supporters and protesters trading blows. The cameras want to know whether you’ll pour water or gasoline.`,
    choices: [
      {
        label: 'Call firmly for calm and decency',
        fx: { support: 8, base: -2, media: 4 },
        set: { peacemaker: true },
        tone: 'good',
        result: 'You condemn the violence on all sides and mean it. Leadership in the ugly moment reads as strength.',
      },
      {
        label: 'Wink at your crowd’s passion',
        fx: { base: 10, heat: 10, support: -8 },
        set: { tyrant_rep: true },
        tone: 'bold',
        result: 'You excuse your side and blame the others. The base loves the fire; the fire does not stay contained.',
      },
    ],
  },
  {
    id: 'p7_b_celebrity_implodes',
    paths: ['ballot'],
    phases: [2, 3],
    weight: 6,
    art: 'rival',
    emoji: '💥',
    title: 'The Backer Implodes',
    body: `The famous supporter you proudly paraded last month has erupted in a scandal of their own. Every photo of the two of you is now being recirculated, helpfully, by your rivals.`,
    choices: [
      {
        label: 'Disavow them immediately and totally',
        fx: { media: 6, support: 4, base: -2 },
        tone: 'slick',
        result: 'You cut them loose within the hour and salt the earth. Cold, fast, and the only move that stops the bleeding.',
      },
      {
        label: 'Stand by them out of loyalty',
        fx: { base: 6, heat: 10, support: -8 },
        set: { loyal_to_old_friends: true },
        tone: 'bold',
        result: 'You refuse to abandon a friend in the storm. Admirable, costly, and now their scandal rents space in yours.',
      },
    ],
  },

  // ---------------- VANGUARD ----------------
  {
    id: 'p7_v_anthem',
    paths: ['vanguard'],
    phases: [3],
    weight: 7,
    art: 'bulletin',
    emoji: '🎵',
    title: 'The New Anthem',
    body: `A committee proposes rewriting a verse of the national anthem to mention your deeds by name. Immortality in song, or a vanity so naked even your allies might wince.`,
    choices: [
      {
        label: 'Approve the verse',
        fx: { base: 8, media: 6, support: -4, heat: 4 },
        set: { own_cult: true },
        tone: 'bold',
        result: 'Schoolchildren now sing your name before breakfast. To be woven into the anthem is a kind of forever, and a kind of warning.',
      },
      {
        label: 'Decline; "the anthem belongs to the people"',
        fx: { support: 10, base: -2 },
        set: { ascetic_rep: true },
        tone: 'good',
        result: 'You refuse the verse with a humble line that itself becomes famous. Modesty, performed well, outshines the medal.',
      },
    ],
  },
  {
    id: 'p7_v_purge_mentor',
    paths: ['vanguard'],
    phases: [2, 3],
    weight: 8,
    art: 'rival',
    emoji: '⚰️',
    title: 'Purge Your Mentor',
    body: `The Centre has decided your old mentor — the one who taught you everything — is now a liability, and they want you, specifically, to be the one who denounces him. A loyalty test with teeth.`,
    choices: [
      {
        label: 'Denounce him to save yourself',
        fx: { influence: 8, base: 6, support: -8, heat: 6 },
        inc: { purge_count: 1 },
        set: { bloody_hands: true },
        tone: 'bold',
        result: 'You read the charges against the man who made you. You pass the test and fail something harder to name.',
      },
      {
        label: 'Refuse, and share his danger',
        fx: { support: 10, influence: -10, heat: 10 },
        set: { honest_rep: true, martyr_rep: true },
        tone: 'good',
        result: 'You will not raise your hand against him, whatever it costs. Loyalty like that is rare here, and rarely free.',
      },
    ],
  },
  {
    id: 'p7_v_foreign_loan',
    paths: ['vanguard'],
    phases: [2, 3],
    weight: 7,
    art: 'scene',
    emoji: '💱',
    title: 'The Foreign Loan',
    body: `A wealthy foreign power offers a loan that would paper over your region’s shortfalls — secured against a strategic harbor and a great deal of future obedience.`,
    choices: [
      {
        label: 'Take the loan, mortgage the harbor',
        fx: { funds: 14, influence: 6, base: -4, heat: 6 },
        set: { foreign_friends: true },
        tone: 'slick',
        result: 'The money solves today and sells tomorrow. The harbor flies your flag and answers, increasingly, to theirs.',
      },
      {
        label: 'Refuse; tighten belts at home',
        fx: { base: 6, support: 4, funds: -6 },
        tone: 'bold',
        result: 'You choose lean independence over comfortable debt. The winter is harder and entirely your own.',
      },
    ],
  },
  {
    id: 'p7_v_youth_brigade',
    paths: ['vanguard'],
    phases: [1, 2],
    weight: 7,
    art: 'bulletin',
    emoji: '🔺',
    title: 'The Youth Brigade',
    body: `Fervent young volunteers want to form a "vanguard brigade" to root out backsliders — passionate, useful, and one bad order away from a mob you can’t recall.`,
    choices: [
      {
        label: 'Arm and unleash them',
        fx: { base: 12, influence: 4, heat: 10, support: -6 },
        inc: { purge_count: 1 },
        set: { tyrant_rep: true, bloody_hands: true },
        tone: 'bold',
        result: 'You hand zeal a mandate and a list. They are terrifyingly effective and, very soon, no longer yours.',
      },
      {
        label: 'Channel their energy into harmless service',
        fx: { base: 6, support: 6, heat: -2 },
        tone: 'good',
        result: 'You point them at litter and harvests instead of neighbors. The fervor cools into something almost wholesome.',
      },
    ],
  },
  {
    id: 'p7_v_model_village',
    paths: ['vanguard'],
    phases: [1, 2],
    weight: 7,
    art: 'scene',
    emoji: '🏘️',
    title: 'The Inspection',
    body: `A high delegation is touring your region. You can show them a real, struggling village, or the gleaming model one your staff built specifically to be toured.`,
    choices: [
      {
        label: 'Show the polished model village',
        fx: { influence: 8, media: 6, heat: 6, support: -4 },
        set: { potemkin: true },
        tone: 'slick',
        result: 'The delegation marvels at the painted prosperity. Your stock rises on a foundation of fresh paint.',
      },
      {
        label: 'Show them the real conditions',
        roll: {
          stat: 'support',
          dc: 52,
          success: {
            fx: { support: 12, influence: 4 },
            text: 'You show the hardship honestly and ask for real help. Candor stuns them into actually sending some.',
          },
          fail: {
            fx: { influence: -6, heat: 6 },
            text: 'The honesty reads as incompetence, not courage. "Why is your region so poor?" is the takeaway.',
          },
        },
        set: { honest_rep: true },
        tone: 'good',
      },
    ],
  },
  {
    id: 'p7_v_archive',
    paths: ['vanguard'],
    phases: [3],
    weight: 8,
    art: 'bulletin',
    emoji: '🗃️',
    title: 'The Secret Archive',
    body: `You have come into possession of the archive — decades of the regime’s crimes, names, orders, graves. Destroy it to protect everyone, or keep it as the ultimate leverage.`,
    choices: [
      {
        label: 'Keep it as leverage over them all',
        fx: { influence: 12, base: 6, heat: 10 },
        set: { has_network: true, blackmailer: true },
        tone: 'slick',
        result: 'You lock the archive away and let it be known, vaguely, that you have it. Suddenly everyone is very polite to you.',
      },
      {
        label: 'Secretly preserve it for history',
        fx: { support: 8, heat: 8, base: -2 },
        set: { secret_reformer: true },
        tone: 'good',
        result: 'You smuggle copies to where the truth can someday surface. A bet on a reckoning you may not live to see.',
      },
      {
        label: 'Burn it; protect the present',
        fx: { base: 6, influence: 4, heat: -6 },
        tone: 'bold',
        result: 'You feed the crimes to the furnace. The names are safe, the graves stay quiet, and history loses an argument.',
      },
    ],
  },
  {
    id: 'p7_v_amnesty',
    paths: ['vanguard'],
    phases: [2, 3],
    weight: 7,
    art: 'bulletin',
    emoji: '🕊️',
    title: 'The Amnesty',
    body: `You could declare an amnesty for a class of minor political prisoners — a genuine mercy, a useful piece of theater, and a gamble that the freed will be grateful rather than emboldened.`,
    choices: [
      {
        label: 'Grant a sweeping, sincere amnesty',
        fx: { support: 12, base: -4, heat: 4 },
        set: { secret_reformer: true, peacemaker: true },
        tone: 'good',
        result: 'You open the gates wider than anyone expected. Most weep with gratitude; a few walk out hungrier than before.',
      },
      {
        label: 'A narrow, well-publicized gesture',
        fx: { media: 8, support: 4, base: 2 },
        tone: 'slick',
        result: 'You free a careful handful in front of cameras. The mercy is real, modest, and precisely calibrated for applause.',
      },
    ],
  },

  // ---------------- SHARED ----------------
  {
    id: 'p7_s_doctored_footage',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 7,
    art: 'newspaper',
    emoji: '🎞️',
    title: 'The Doctored Footage',
    body: `A convincing fabricated video of you saying something monstrous is racing across the country. By the time the experts debunk it, millions will have already believed their eyes.`,
    choices: [
      {
        label: 'Flood the zone with the debunking',
        roll: {
          stat: 'media',
          dc: 53,
          success: {
            fx: { media: 8, support: 8, heat: -4 },
            text: 'You prove the fake fast and loud and turn it into a story about your enemies’ dirty tricks. Reversed.',
          },
          fail: {
            fx: { support: -10, heat: 8 },
            text: 'The truth limps out after the lie has sprinted around the country. "I never said that" rarely catches up.',
          },
        },
        tone: 'bold',
      },
      {
        label: 'Use it to discredit all unflattering footage',
        fx: { base: 6, heat: 8, media: -2 },
        set: { stonewaller: true },
        tone: 'slick',
        result: 'You declare everything inconvenient a "fake" from now on. Handy, corrosive, and it cuts both ways forever.',
      },
    ],
  },
  {
    id: 'p7_s_old_photo',
    paths: ['ballot', 'vanguard'],
    phases: [1, 2, 3],
    weight: 6,
    art: 'newspaper',
    emoji: '📸',
    title: 'The Old Photograph',
    body: `A photo from your reckless youth has surfaced — nothing criminal, but mortifying and easy to caricature. It is climbing, captioned by people who were not there.`,
    choices: [
      {
        label: 'Laugh it off and tell the real story',
        fx: { support: 8, media: 4, base: 2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You share the embarrassing backstory yourself, warts and laughs included. Humanized, the photo loses its sting.',
      },
      {
        label: 'Try to scrub it from everywhere',
        fx: { heat: 8, support: -4 },
        tone: 'slick',
        result: 'You sic lawyers on every repost. The takedown notices become the story, and the photo multiplies in spite.',
      },
    ],
  },
  {
    id: 'p7_s_charity_front',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 6,
    art: 'scene',
    emoji: '🎗️',
    title: 'The Foundation',
    body: `A charitable foundation in your name does real good — and, conveniently, also functions as a slush fund and a soft way for the eager to buy access. The books are getting interesting.`,
    choices: [
      {
        label: 'Clean it up and firewall the giving',
        fx: { support: 8, funds: -4, heat: -4 },
        set: { clean_streak: true },
        tone: 'good',
        result: 'You sever the access game from the actual charity. Less useful as a tool, far safer as a legacy.',
      },
      {
        label: 'Keep the access machine humming',
        fx: { funds: 10, influence: 6, heat: 8 },
        set: { corrupt_streak: true },
        scandal: { id: 'foundation_slush', label: 'the foundation’s convenient books', severity: 2 },
        tone: 'slick',
        result: 'You let the donations and the favors keep mingling. Efficient, lucrative, and exactly the sort of thing auditors love.',
      },
    ],
  },
  {
    id: 'p7_s_whistleblower',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 7,
    art: 'scene',
    emoji: '📣',
    title: 'The Whistleblower',
    body: `Someone inside your own operation is preparing to expose a genuine wrong you committed. You can address the wrong, or address the whistleblower.`,
    choices: [
      {
        label: 'Fix the wrong before they have to expose it',
        fx: { support: 8, influence: -2, heat: -6 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You correct the problem and quietly thank the conscience that flagged it. The story dies because the wrong does.',
      },
      {
        label: 'Discredit and isolate the whistleblower',
        fx: { base: 4, heat: 10, support: -6 },
        inc: { purge_count: 1 },
        set: { bloody_hands: true },
        scandal: { id: 'whistleblower_smear', label: 'the whistleblower you buried', severity: 3 },
        tone: 'bold',
        result: 'You destroy the messenger and leave the message intact. It works, until the next person with a conscience.',
      },
    ],
  },
  {
    id: 'p7_s_translator',
    paths: ['ballot', 'vanguard'],
    phases: [1, 2, 3],
    weight: 6,
    art: 'scene',
    emoji: '🗣️',
    title: 'Lost in Translation',
    body: `At a tense foreign meeting, your translator botches a phrase and your hosts stiffen, insulted by something you never meant. The room cools by ten degrees in an instant.`,
    choices: [
      {
        label: 'Stop, apologize warmly, and clarify yourself',
        fx: { influence: 8, support: 4 },
        set: { peacemaker: true },
        tone: 'good',
        result: 'You catch it, laugh at the error, and make the apology personal. Grace repairs the room and impresses your hosts.',
      },
      {
        label: 'Bluff past it and pretend not to notice',
        roll: {
          stat: 'influence',
          dc: 50,
          success: {
            fx: { influence: 6, base: 2 },
            text: 'You steer the talk onward so smoothly the slight is forgotten. Sometimes nerve beats a correction.',
          },
          fail: {
            fx: { influence: -6, heat: 4 },
            text: 'The insult festers unaddressed and the meeting curdles. The silence becomes the story your hosts tell.',
          },
        },
        tone: 'slick',
      },
    ],
  },
  {
    id: 'p7_s_exhaustion',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 6,
    art: 'scene',
    emoji: '🌙',
    title: 'Running on Empty',
    body: `Months of eighteen-hour days have caught up with you, and the decisions are starting to blur. You can power through on willpower or finally trust your team with real authority.`,
    choices: [
      {
        label: 'Delegate genuine authority to your team',
        fx: { influence: 8, support: 4, base: 2 },
        set: { has_network: true },
        tone: 'good',
        result: 'You hand real power to people you trust and, miraculously, the machine runs better. Strength can look like letting go.',
      },
      {
        label: 'Power through alone on willpower',
        roll: {
          stat: 'base',
          dc: 52,
          success: {
            fx: { base: 6, support: 4 },
            text: 'You grind through the wall and out the other side. The legend of your stamina grows another inch.',
          },
          fail: {
            fx: { support: -6, heat: 4 },
            text: 'A blurry, exhausted decision goes badly wrong. The error was avoidable, and avoidable errors are the worst kind.',
          },
        },
        tone: 'bold',
      },
    ],
  },

  // ---------------- CRISES ----------------
  {
    id: 'p7_c_nuclear',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 9,
    crisis: true,
    art: 'crisis',
    emoji: '☢️',
    title: 'The Reactor Alarm',
    body: `A reactor is venting and the readings are climbing. Evacuate a million people on a maybe, or trust the engineers’ word that they can contain it before the wind shifts.`,
    choices: [
      {
        label: 'Evacuate now, apologize later',
        roll: {
          stat: 'support',
          dc: 50,
          success: {
            fx: { support: 12, influence: 6, funds: -8 },
            text: 'You move a million people on a precaution. The reactor is contained; your "overreaction" saved a region from a maybe.',
          },
          fail: {
            fx: { support: -4, heat: 4 },
            text: 'You empty cities and the reactor holds fine. The panic and cost are blamed on you; the disaster that didn’t happen earns no thanks.',
          },
        },
        tone: 'good',
      },
      {
        label: 'Trust containment, keep it quiet',
        fx: { influence: 4, heat: 12, support: -6 },
        scandal: { id: 'reactor_silence', label: 'the reactor scare you sat on', severity: 3 },
        tone: 'slick',
        result: 'You bet on the engineers and say nothing. If they’re right, no one ever knows. If they’re wrong, everyone does.',
      },
    ],
  },
  {
    id: 'p7_c_ally_killed',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 8,
    crisis: true,
    art: 'crisis',
    emoji: '🕯️',
    title: 'The Ally Is Killed',
    body: `Your closest political ally has been assassinated, and the nation is reeling and enraged. The pressure to name a culprit and strike back is enormous and immediate.`,
    choices: [
      {
        label: 'Grieve, investigate, resist vengeance',
        roll: {
          stat: 'support',
          dc: 53,
          success: {
            fx: { support: 12, base: 6, influence: 4 },
            text: 'You honor your friend with patience instead of a posse. The killers are found properly; the country holds.',
          },
          fail: {
            fx: { support: -6, heat: 6 },
            text: 'Your restraint enrages a public that wanted blood. Mourning, they decide, is not the same as leading.',
          },
        },
        set: { peacemaker: true },
        tone: 'good',
      },
      {
        label: 'Avenge them; round up the "responsible"',
        fx: { base: 10, heat: 14, support: -4 },
        inc: { purge_count: 2 },
        set: { bloody_hands: true, tyrant_rep: true },
        tone: 'bold',
        result: 'You answer murder with a sweep of arrests, evidence optional. Grief becomes a warrant, and the warrant is wide.',
      },
    ],
  },
  {
    id: 'p7_c_winter',
    paths: ['ballot', 'vanguard'],
    phases: [1, 2, 3],
    weight: 8,
    crisis: true,
    art: 'crisis',
    emoji: '❄️',
    title: 'The Cold Snap',
    body: `A brutal winter has outrun the fuel supply, and people are starting to freeze in their homes. There is enough heat for the cities or the countryside, but not both.`,
    choices: [
      {
        label: 'Share the shortage and ask sacrifice of all',
        fx: { support: 10, base: 4, influence: -2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You ration heat evenly, dim the capital’s lights first, and lead by shivering too. Shared cold, shared respect.',
      },
      {
        label: 'Keep the cities warm, let the margins freeze',
        fx: { base: 6, influence: 6, support: -10, heat: 8 },
        scandal: { id: 'cold_margins', label: 'the villages you left to freeze', severity: 2 },
        tone: 'slick',
        result: 'You keep the powerful warm and the forgotten cold. The math is sound; the map of who froze is not forgotten.',
      },
    ],
  },
  {
    id: 'p7_c_mutiny',
    paths: ['ballot', 'vanguard'],
    phases: [2, 3],
    weight: 8,
    crisis: true,
    art: 'crisis',
    emoji: '⚓',
    title: 'The Mutiny',
    body: `A garrison has refused orders and barricaded itself, airing grievances that are, inconveniently, half-legitimate. Negotiate with mutineers, or make an example before it spreads.`,
    choices: [
      {
        label: 'Hear them out; address the grievances',
        roll: {
          stat: 'support',
          dc: 52,
          success: {
            fx: { support: 12, base: 6, influence: 4 },
            text: 'You meet the mutineers, concede what’s fair, and fold them back in with honor. The contagion never starts.',
          },
          fail: {
            fx: { support: -6, heat: 8 },
            text: 'Your leniency emboldens a second garrison to try the same. Mercy, misread, can look like an open door.',
          },
        },
        tone: 'good',
      },
      {
        label: 'Crush the mutiny hard and fast',
        fx: { base: 10, heat: 14, support: -8 },
        inc: { purge_count: 1 },
        set: { bloody_hands: true, tyrant_rep: true },
        tone: 'bold',
        result: 'You retake the garrison by force and discipline survivors publicly. The fleet falls silent — out of fear, which is not the same as loyalty.',
      },
    ],
  },
  {
    id: 'p7_c_rail',
    paths: ['ballot', 'vanguard'],
    phases: [1, 2, 3],
    weight: 8,
    crisis: true,
    art: 'crisis',
    emoji: '🚆',
    title: 'The Rail Disaster',
    body: `A packed train has derailed with terrible loss, and early signs point to deferred maintenance your own budget cut. The grief is immediate; the paper trail is patient.`,
    choices: [
      {
        label: 'Take responsibility and overhaul safety',
        fx: { support: 10, funds: -10, heat: -2 },
        set: { honest_rep: true },
        tone: 'good',
        result: 'You own the failure, fund the fix, and visit every family. Accountability is expensive and, here, exactly right.',
      },
      {
        label: 'Blame the operators and bury the budget memo',
        roll: {
          stat: 'media',
          dc: 53,
          success: {
            fx: { media: 6, base: 4, heat: 4 },
            text: 'You pin it on a tired driver and the memo stays in its drawer. The story moves on, for now.',
          },
          fail: {
            fx: { support: -12, heat: 12 },
            text: 'The budget memo leaks with your signature on the cuts. The cover-up dwarfs the original failure.',
          },
        },
        scandal: { id: 'rail_memo', label: 'the maintenance cuts you hid', severity: 3 },
        tone: 'slick',
      },
    ],
  },
];
